/********************************************************************************
** Form generated from reading UI file 'LIGHTWalkingDialog.ui'
**
** Created by: Qt User Interface Compiler version 5.9.8
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_LIGHTWALKINGDIALOG_H
#define UI_LIGHTWALKINGDIALOG_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_LIGHTWalkingDialog
{
public:
    QLabel *label;
    QPushButton *BTN_JOINTSPACE_MOVE_GO;
    QPushButton *BTN_WORKSPACE_MOVE_GO;
    QLabel *label_10;
    QGroupBox *groupBox;
    QRadioButton *RBTN_OPERATIONMODE_ROBOT;
    QRadioButton *RBTN_OPERATIONMODE_CHOREONOID;
    QLabel *label_46;
    QLineEdit *LE_ROBOT_OR_SIM;
    QLineEdit *CON_WORKSPACE_RIGHT_X;
    QLineEdit *CON_WORKSPACE_RIGHT_Z;
    QLineEdit *CON_WORKSPACE_RIGHT_Y;
    QLabel *label_11;
    QLabel *label_12;
    QLineEdit *CON_WORKSPACE_LEFT_Y;
    QLineEdit *CON_WORKSPACE_LEFT_X;
    QLineEdit *CON_WORKSPACE_LEFT_Z;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLineEdit *CON_WORKSPACE_TIME;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_25;
    QLabel *label_20;
    QLineEdit *CON_COMMOVE_Z;
    QLineEdit *CON_COMMOVE_X;
    QLabel *label_22;
    QLineEdit *CON_COMMOVE_Y;
    QLabel *label_19;
    QLineEdit *CON_COMMOVE_TIME;
    QPushButton *BTN_COMMOVE_GO;
    QLabel *label_21;
    QPushButton *BTN_SAVE_START;
    QPushButton *BTN_SAVE_END;
    QLineEdit *CON_COMMOVE_PELVIS_PITCH;
    QLabel *label_38;
    QLabel *label_39;
    QGroupBox *groupBox_4;
    QPushButton *BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_POS;
    QCheckBox *CBX_ROBOT_CONTROLMETHOD_RHY;
    QCheckBox *CBX_ROBOT_CONTROLMETHOD_RHR;
    QCheckBox *CBX_ROBOT_CONTROLMETHOD_RHP;
    QCheckBox *CBX_ROBOT_CONTROLMETHOD_RKN;
    QCheckBox *CBX_ROBOT_CONTROLMETHOD_RANK;
    QCheckBox *CBX_ROBOT_CONTROLMETHOD_LHY;
    QCheckBox *CBX_ROBOT_CONTROLMETHOD_LANK;
    QCheckBox *CBX_ROBOT_CONTROLMETHOD_LHP;
    QCheckBox *CBX_ROBOT_CONTROLMETHOD_LHR;
    QCheckBox *CBX_ROBOT_CONTROLMETHOD_LKN;
    QPushButton *BTN_ROBOT_CONTROLMETHOD_CHANGE;
    QPushButton *BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_TOR;
    QLabel *label_42;
    QGroupBox *groupBox_3;
    QPushButton *BTN_IMU_NULL;
    QLineEdit *LE_IMU_ROLL;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QPushButton *BTN_IMU_RESET;
    QPushButton *BTN_IMU_ENABLE;
    QPushButton *BTN_IMU_DISABLE;
    QLineEdit *LE_IMU_PITCH;
    QLineEdit *LE_IMU_YAW;
    QGroupBox *groupBox_2;
    QRadioButton *RBTN_COM_REFFRAME_LF;
    QRadioButton *RBTN_COM_REFFRAME_RF;
    QLabel *label_29;
    QPushButton *BTN_SUPPORT_TRANSITION_RDSP2RSSP;
    QPushButton *BTN_SUPPORT_TRANSITION_RDSP2LDSP;
    QPushButton *BTN_SUPPORT_TRANSITION_LDSP2LSSP;
    QPushButton *BTN_SUPPORT_TRANSITION_LSSP2LDSP;
    QPushButton *BTN_SUPPORT_TRANSITION_RSSP2RDSP;
    QPushButton *BTN_SUPPORT_TRANSITION_LDSP2RDSP;
    QFrame *frame;
    QPushButton *BTN_SYSID_COMREF2ZMP_SSP_LF_X;
    QPushButton *BTN_SYSID_COMREF2ZMP_DSP_LF_Y;
    QLabel *label_63;
    QLineEdit *CON_SYSID_COMREF2ZMP_DFREQ;
    QLabel *label_62;
    QLineEdit *CON_SYSID_COMREF2ZMP_NUM;
    QPushButton *BTN_SYSID_COMREF2ZMP_DSP_RF_Y;
    QPushButton *BTN_SYSID_COMREF2ZMP_SSP_RF_X;
    QPushButton *BTN_SYSID_COMREF2ZMP_DSP_LF_X;
    QLabel *label_66;
    QLineEdit *CON_SYSID_COMREF2ZMP_COMMAG;
    QPushButton *BTN_SYSID_COMREF2ZMP_DSP_RF_X;
    QLabel *label_64;
    QPushButton *BTN_SYSID_COMREF2ZMP_SSP_RF_Y;
    QPushButton *BTN_SYSID_COMREF2ZMP_SSP_LF_Y;
    QLineEdit *CON_COMMOVE_SSP_TIME;
    QPushButton *BTN_COMMOVE_SSP_GO;
    QLabel *label_26;
    QLabel *label_30;
    QLabel *label_31;
    QLineEdit *CON_COMMOVE_SSP_SWING_X;
    QLineEdit *CON_COMMOVE_SSP_SWING_Y;
    QLabel *label_34;
    QLineEdit *CON_COMMOVE_SSP_SWING_Z;
    QLabel *label_35;
    QFrame *frame_2;
    QRadioButton *RBTN_COM_SSP_REFFRAME_RF;
    QRadioButton *RBTN_COM_SSP_REFFRAME_LF;
    QLineEdit *CON_SAVE_FILENAME;
    QLabel *label_23;
    QPushButton *BTN_KINEMATIC_COMPENSATION_ON;
    QPushButton *BTN_KINEMATIC_COMPENSATION_OFF;
    QPushButton *BTN_SQUAT_GO;
    QLineEdit *CON_SQUAT_NUMBER;
    QFrame *frame_3;
    QRadioButton *RBTN_SQUAT_MODE_DSP;
    QRadioButton *RBTN_SQUAT_MODE_SSP;
    QLineEdit *CON_SQUAT_PERIOD;
    QLineEdit *CON_SQUAT_HEIGHT;
    QLabel *label_27;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_33;
    QLineEdit *CON_AIRWALKING_STRIDE;
    QLabel *label_3;
    QLabel *label_4;
    QLineEdit *CON_AIRWALKING_STEPTIME;
    QLabel *label_5;
    QPushButton *BTN_AIRWALKING_GO;
    QLabel *label_7;
    QLabel *label_2;
    QLineEdit *CON_AIRWALKING_NUM;
    QLabel *label_6;
    QLabel *label_8;

    void setupUi(QWidget *LIGHTWalkingDialog)
    {
        if (LIGHTWalkingDialog->objectName().isEmpty())
            LIGHTWalkingDialog->setObjectName(QStringLiteral("LIGHTWalkingDialog"));
        LIGHTWalkingDialog->resize(780, 780);
        label = new QLabel(LIGHTWalkingDialog);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(250, 10, 261, 31));
        QFont font;
        font.setPointSize(12);
        label->setFont(font);
        label->setAlignment(Qt::AlignCenter);
        BTN_JOINTSPACE_MOVE_GO = new QPushButton(LIGHTWalkingDialog);
        BTN_JOINTSPACE_MOVE_GO->setObjectName(QStringLiteral("BTN_JOINTSPACE_MOVE_GO"));
        BTN_JOINTSPACE_MOVE_GO->setGeometry(QRect(180, 300, 91, 91));
        QFont font1;
        font1.setPointSize(10);
        BTN_JOINTSPACE_MOVE_GO->setFont(font1);
        BTN_WORKSPACE_MOVE_GO = new QPushButton(LIGHTWalkingDialog);
        BTN_WORKSPACE_MOVE_GO->setObjectName(QStringLiteral("BTN_WORKSPACE_MOVE_GO"));
        BTN_WORKSPACE_MOVE_GO->setGeometry(QRect(450, 280, 51, 91));
        label_10 = new QLabel(LIGHTWalkingDialog);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(320, 218, 171, 16));
        groupBox = new QGroupBox(LIGHTWalkingDialog);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(19, 50, 211, 91));
        groupBox->setAlignment(Qt::AlignCenter);
        RBTN_OPERATIONMODE_ROBOT = new QRadioButton(groupBox);
        RBTN_OPERATIONMODE_ROBOT->setObjectName(QStringLiteral("RBTN_OPERATIONMODE_ROBOT"));
        RBTN_OPERATIONMODE_ROBOT->setGeometry(QRect(24, 30, 100, 21));
        RBTN_OPERATIONMODE_ROBOT->setChecked(true);
        RBTN_OPERATIONMODE_CHOREONOID = new QRadioButton(groupBox);
        RBTN_OPERATIONMODE_CHOREONOID->setObjectName(QStringLiteral("RBTN_OPERATIONMODE_CHOREONOID"));
        RBTN_OPERATIONMODE_CHOREONOID->setGeometry(QRect(94, 30, 100, 21));
        label_46 = new QLabel(groupBox);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(13, 62, 161, 16));
        label_46->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        LE_ROBOT_OR_SIM = new QLineEdit(groupBox);
        LE_ROBOT_OR_SIM->setObjectName(QStringLiteral("LE_ROBOT_OR_SIM"));
        LE_ROBOT_OR_SIM->setGeometry(QRect(110, 58, 91, 23));
        LE_ROBOT_OR_SIM->setAlignment(Qt::AlignCenter);
        LE_ROBOT_OR_SIM->setReadOnly(true);
        CON_WORKSPACE_RIGHT_X = new QLineEdit(LIGHTWalkingDialog);
        CON_WORKSPACE_RIGHT_X->setObjectName(QStringLiteral("CON_WORKSPACE_RIGHT_X"));
        CON_WORKSPACE_RIGHT_X->setGeometry(QRect(345, 276, 41, 23));
        CON_WORKSPACE_RIGHT_X->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        CON_WORKSPACE_RIGHT_Z = new QLineEdit(LIGHTWalkingDialog);
        CON_WORKSPACE_RIGHT_Z->setObjectName(QStringLiteral("CON_WORKSPACE_RIGHT_Z"));
        CON_WORKSPACE_RIGHT_Z->setGeometry(QRect(345, 330, 41, 23));
        CON_WORKSPACE_RIGHT_Z->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        CON_WORKSPACE_RIGHT_Y = new QLineEdit(LIGHTWalkingDialog);
        CON_WORKSPACE_RIGHT_Y->setObjectName(QStringLiteral("CON_WORKSPACE_RIGHT_Y"));
        CON_WORKSPACE_RIGHT_Y->setGeometry(QRect(345, 303, 41, 23));
        CON_WORKSPACE_RIGHT_Y->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_11 = new QLabel(LIGHTWalkingDialog);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(339, 250, 51, 16));
        label_11->setAlignment(Qt::AlignCenter);
        label_12 = new QLabel(LIGHTWalkingDialog);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(389, 250, 51, 16));
        label_12->setAlignment(Qt::AlignCenter);
        CON_WORKSPACE_LEFT_Y = new QLineEdit(LIGHTWalkingDialog);
        CON_WORKSPACE_LEFT_Y->setObjectName(QStringLiteral("CON_WORKSPACE_LEFT_Y"));
        CON_WORKSPACE_LEFT_Y->setGeometry(QRect(393, 303, 41, 23));
        CON_WORKSPACE_LEFT_Y->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        CON_WORKSPACE_LEFT_X = new QLineEdit(LIGHTWalkingDialog);
        CON_WORKSPACE_LEFT_X->setObjectName(QStringLiteral("CON_WORKSPACE_LEFT_X"));
        CON_WORKSPACE_LEFT_X->setGeometry(QRect(393, 276, 41, 23));
        CON_WORKSPACE_LEFT_X->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        CON_WORKSPACE_LEFT_Z = new QLineEdit(LIGHTWalkingDialog);
        CON_WORKSPACE_LEFT_Z->setObjectName(QStringLiteral("CON_WORKSPACE_LEFT_Z"));
        CON_WORKSPACE_LEFT_Z->setGeometry(QRect(393, 330, 41, 23));
        CON_WORKSPACE_LEFT_Z->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_13 = new QLabel(LIGHTWalkingDialog);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(299, 280, 41, 16));
        label_13->setAlignment(Qt::AlignCenter);
        label_14 = new QLabel(LIGHTWalkingDialog);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(299, 305, 41, 16));
        label_14->setAlignment(Qt::AlignCenter);
        label_15 = new QLabel(LIGHTWalkingDialog);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(299, 332, 41, 16));
        label_15->setAlignment(Qt::AlignCenter);
        label_16 = new QLabel(LIGHTWalkingDialog);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(300, 360, 41, 16));
        label_16->setAlignment(Qt::AlignCenter);
        CON_WORKSPACE_TIME = new QLineEdit(LIGHTWalkingDialog);
        CON_WORKSPACE_TIME->setObjectName(QStringLiteral("CON_WORKSPACE_TIME"));
        CON_WORKSPACE_TIME->setGeometry(QRect(345, 357, 41, 23));
        CON_WORKSPACE_TIME->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_17 = new QLabel(LIGHTWalkingDialog);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(380, 360, 41, 16));
        label_17->setAlignment(Qt::AlignCenter);
        label_18 = new QLabel(LIGHTWalkingDialog);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(535, 216, 201, 16));
        label_18->setAlignment(Qt::AlignCenter);
        label_25 = new QLabel(LIGHTWalkingDialog);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(550, 353, 41, 16));
        label_25->setAlignment(Qt::AlignCenter);
        label_20 = new QLabel(LIGHTWalkingDialog);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(630, 353, 41, 16));
        label_20->setAlignment(Qt::AlignCenter);
        CON_COMMOVE_Z = new QLineEdit(LIGHTWalkingDialog);
        CON_COMMOVE_Z->setObjectName(QStringLiteral("CON_COMMOVE_Z"));
        CON_COMMOVE_Z->setGeometry(QRect(595, 296, 40, 23));
        CON_COMMOVE_Z->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        CON_COMMOVE_X = new QLineEdit(LIGHTWalkingDialog);
        CON_COMMOVE_X->setObjectName(QStringLiteral("CON_COMMOVE_X"));
        CON_COMMOVE_X->setGeometry(QRect(595, 242, 40, 23));
        CON_COMMOVE_X->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_22 = new QLabel(LIGHTWalkingDialog);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(515, 298, 71, 20));
        label_22->setAlignment(Qt::AlignCenter);
        CON_COMMOVE_Y = new QLineEdit(LIGHTWalkingDialog);
        CON_COMMOVE_Y->setObjectName(QStringLiteral("CON_COMMOVE_Y"));
        CON_COMMOVE_Y->setGeometry(QRect(595, 269, 40, 23));
        CON_COMMOVE_Y->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_19 = new QLabel(LIGHTWalkingDialog);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(549, 246, 41, 16));
        label_19->setAlignment(Qt::AlignCenter);
        CON_COMMOVE_TIME = new QLineEdit(LIGHTWalkingDialog);
        CON_COMMOVE_TIME->setObjectName(QStringLiteral("CON_COMMOVE_TIME"));
        CON_COMMOVE_TIME->setGeometry(QRect(595, 350, 40, 23));
        CON_COMMOVE_TIME->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        BTN_COMMOVE_GO = new QPushButton(LIGHTWalkingDialog);
        BTN_COMMOVE_GO->setObjectName(QStringLiteral("BTN_COMMOVE_GO"));
        BTN_COMMOVE_GO->setGeometry(QRect(675, 330, 61, 41));
        label_21 = new QLabel(LIGHTWalkingDialog);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(549, 271, 41, 16));
        label_21->setAlignment(Qt::AlignCenter);
        BTN_SAVE_START = new QPushButton(LIGHTWalkingDialog);
        BTN_SAVE_START->setObjectName(QStringLiteral("BTN_SAVE_START"));
        BTN_SAVE_START->setGeometry(QRect(20, 330, 141, 31));
        BTN_SAVE_END = new QPushButton(LIGHTWalkingDialog);
        BTN_SAVE_END->setObjectName(QStringLiteral("BTN_SAVE_END"));
        BTN_SAVE_END->setGeometry(QRect(20, 370, 141, 31));
        CON_COMMOVE_PELVIS_PITCH = new QLineEdit(LIGHTWalkingDialog);
        CON_COMMOVE_PELVIS_PITCH->setObjectName(QStringLiteral("CON_COMMOVE_PELVIS_PITCH"));
        CON_COMMOVE_PELVIS_PITCH->setGeometry(QRect(595, 323, 40, 23));
        CON_COMMOVE_PELVIS_PITCH->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_38 = new QLabel(LIGHTWalkingDialog);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(517, 325, 71, 20));
        label_38->setAlignment(Qt::AlignCenter);
        label_39 = new QLabel(LIGHTWalkingDialog);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(630, 327, 41, 16));
        label_39->setAlignment(Qt::AlignCenter);
        groupBox_4 = new QGroupBox(LIGHTWalkingDialog);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(262, 52, 481, 151));
        groupBox_4->setAlignment(Qt::AlignCenter);
        BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_POS = new QPushButton(groupBox_4);
        BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_POS->setObjectName(QStringLiteral("BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_POS"));
        BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_POS->setEnabled(true);
        BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_POS->setGeometry(QRect(30, 110, 201, 31));
        CBX_ROBOT_CONTROLMETHOD_RHY = new QCheckBox(groupBox_4);
        CBX_ROBOT_CONTROLMETHOD_RHY->setObjectName(QStringLiteral("CBX_ROBOT_CONTROLMETHOD_RHY"));
        CBX_ROBOT_CONTROLMETHOD_RHY->setEnabled(false);
        CBX_ROBOT_CONTROLMETHOD_RHY->setGeometry(QRect(80, 30, 51, 20));
        CBX_ROBOT_CONTROLMETHOD_RHR = new QCheckBox(groupBox_4);
        CBX_ROBOT_CONTROLMETHOD_RHR->setObjectName(QStringLiteral("CBX_ROBOT_CONTROLMETHOD_RHR"));
        CBX_ROBOT_CONTROLMETHOD_RHR->setEnabled(true);
        CBX_ROBOT_CONTROLMETHOD_RHR->setGeometry(QRect(20, 30, 51, 20));
        CBX_ROBOT_CONTROLMETHOD_RHP = new QCheckBox(groupBox_4);
        CBX_ROBOT_CONTROLMETHOD_RHP->setObjectName(QStringLiteral("CBX_ROBOT_CONTROLMETHOD_RHP"));
        CBX_ROBOT_CONTROLMETHOD_RHP->setEnabled(true);
        CBX_ROBOT_CONTROLMETHOD_RHP->setGeometry(QRect(140, 30, 51, 20));
        CBX_ROBOT_CONTROLMETHOD_RKN = new QCheckBox(groupBox_4);
        CBX_ROBOT_CONTROLMETHOD_RKN->setObjectName(QStringLiteral("CBX_ROBOT_CONTROLMETHOD_RKN"));
        CBX_ROBOT_CONTROLMETHOD_RKN->setGeometry(QRect(200, 30, 51, 20));
        CBX_ROBOT_CONTROLMETHOD_RANK = new QCheckBox(groupBox_4);
        CBX_ROBOT_CONTROLMETHOD_RANK->setObjectName(QStringLiteral("CBX_ROBOT_CONTROLMETHOD_RANK"));
        CBX_ROBOT_CONTROLMETHOD_RANK->setGeometry(QRect(260, 30, 91, 20));
        CBX_ROBOT_CONTROLMETHOD_LHY = new QCheckBox(groupBox_4);
        CBX_ROBOT_CONTROLMETHOD_LHY->setObjectName(QStringLiteral("CBX_ROBOT_CONTROLMETHOD_LHY"));
        CBX_ROBOT_CONTROLMETHOD_LHY->setEnabled(false);
        CBX_ROBOT_CONTROLMETHOD_LHY->setGeometry(QRect(80, 60, 51, 20));
        CBX_ROBOT_CONTROLMETHOD_LANK = new QCheckBox(groupBox_4);
        CBX_ROBOT_CONTROLMETHOD_LANK->setObjectName(QStringLiteral("CBX_ROBOT_CONTROLMETHOD_LANK"));
        CBX_ROBOT_CONTROLMETHOD_LANK->setGeometry(QRect(260, 60, 91, 20));
        CBX_ROBOT_CONTROLMETHOD_LHP = new QCheckBox(groupBox_4);
        CBX_ROBOT_CONTROLMETHOD_LHP->setObjectName(QStringLiteral("CBX_ROBOT_CONTROLMETHOD_LHP"));
        CBX_ROBOT_CONTROLMETHOD_LHP->setEnabled(true);
        CBX_ROBOT_CONTROLMETHOD_LHP->setGeometry(QRect(140, 60, 51, 20));
        CBX_ROBOT_CONTROLMETHOD_LHR = new QCheckBox(groupBox_4);
        CBX_ROBOT_CONTROLMETHOD_LHR->setObjectName(QStringLiteral("CBX_ROBOT_CONTROLMETHOD_LHR"));
        CBX_ROBOT_CONTROLMETHOD_LHR->setEnabled(true);
        CBX_ROBOT_CONTROLMETHOD_LHR->setGeometry(QRect(20, 60, 51, 20));
        CBX_ROBOT_CONTROLMETHOD_LKN = new QCheckBox(groupBox_4);
        CBX_ROBOT_CONTROLMETHOD_LKN->setObjectName(QStringLiteral("CBX_ROBOT_CONTROLMETHOD_LKN"));
        CBX_ROBOT_CONTROLMETHOD_LKN->setGeometry(QRect(200, 60, 51, 20));
        BTN_ROBOT_CONTROLMETHOD_CHANGE = new QPushButton(groupBox_4);
        BTN_ROBOT_CONTROLMETHOD_CHANGE->setObjectName(QStringLiteral("BTN_ROBOT_CONTROLMETHOD_CHANGE"));
        BTN_ROBOT_CONTROLMETHOD_CHANGE->setGeometry(QRect(365, 35, 101, 41));
        BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_TOR = new QPushButton(groupBox_4);
        BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_TOR->setObjectName(QStringLiteral("BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_TOR"));
        BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_TOR->setEnabled(true);
        BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_TOR->setGeometry(QRect(250, 110, 201, 31));
        label_42 = new QLabel(groupBox_4);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(50, 86, 381, 16));
        label_42->setAlignment(Qt::AlignCenter);
        groupBox_3 = new QGroupBox(LIGHTWalkingDialog);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(20, 150, 211, 131));
        groupBox_3->setAlignment(Qt::AlignCenter);
        BTN_IMU_NULL = new QPushButton(groupBox_3);
        BTN_IMU_NULL->setObjectName(QStringLiteral("BTN_IMU_NULL"));
        BTN_IMU_NULL->setGeometry(QRect(110, 78, 91, 21));
        LE_IMU_ROLL = new QLineEdit(groupBox_3);
        LE_IMU_ROLL->setObjectName(QStringLiteral("LE_IMU_ROLL"));
        LE_IMU_ROLL->setGeometry(QRect(31, 34, 61, 23));
        LE_IMU_ROLL->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        LE_IMU_ROLL->setReadOnly(true);
        label_43 = new QLabel(groupBox_3);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(11, 38, 16, 16));
        label_43->setAlignment(Qt::AlignCenter);
        label_44 = new QLabel(groupBox_3);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(10, 70, 21, 16));
        label_44->setAlignment(Qt::AlignCenter);
        label_45 = new QLabel(groupBox_3);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(10, 100, 20, 20));
        label_45->setAlignment(Qt::AlignCenter);
        BTN_IMU_RESET = new QPushButton(groupBox_3);
        BTN_IMU_RESET->setObjectName(QStringLiteral("BTN_IMU_RESET"));
        BTN_IMU_RESET->setGeometry(QRect(110, 100, 91, 21));
        BTN_IMU_ENABLE = new QPushButton(groupBox_3);
        BTN_IMU_ENABLE->setObjectName(QStringLiteral("BTN_IMU_ENABLE"));
        BTN_IMU_ENABLE->setGeometry(QRect(110, 28, 91, 21));
        BTN_IMU_DISABLE = new QPushButton(groupBox_3);
        BTN_IMU_DISABLE->setObjectName(QStringLiteral("BTN_IMU_DISABLE"));
        BTN_IMU_DISABLE->setGeometry(QRect(110, 50, 91, 21));
        LE_IMU_PITCH = new QLineEdit(groupBox_3);
        LE_IMU_PITCH->setObjectName(QStringLiteral("LE_IMU_PITCH"));
        LE_IMU_PITCH->setGeometry(QRect(30, 66, 61, 23));
        LE_IMU_PITCH->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        LE_IMU_PITCH->setReadOnly(true);
        LE_IMU_YAW = new QLineEdit(groupBox_3);
        LE_IMU_YAW->setObjectName(QStringLiteral("LE_IMU_YAW"));
        LE_IMU_YAW->setGeometry(QRect(30, 98, 61, 23));
        LE_IMU_YAW->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        LE_IMU_YAW->setReadOnly(true);
        groupBox_2 = new QGroupBox(LIGHTWalkingDialog);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(675, 230, 61, 80));
        RBTN_COM_REFFRAME_LF = new QRadioButton(groupBox_2);
        RBTN_COM_REFFRAME_LF->setObjectName(QStringLiteral("RBTN_COM_REFFRAME_LF"));
        RBTN_COM_REFFRAME_LF->setGeometry(QRect(13, 54, 61, 21));
        RBTN_COM_REFFRAME_LF->setChecked(false);
        RBTN_COM_REFFRAME_RF = new QRadioButton(groupBox_2);
        RBTN_COM_REFFRAME_RF->setObjectName(QStringLiteral("RBTN_COM_REFFRAME_RF"));
        RBTN_COM_REFFRAME_RF->setGeometry(QRect(13, 26, 61, 21));
        RBTN_COM_REFFRAME_RF->setChecked(true);
        label_29 = new QLabel(LIGHTWalkingDialog);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(563, 610, 191, 16));
        label_29->setAlignment(Qt::AlignCenter);
        BTN_SUPPORT_TRANSITION_RDSP2RSSP = new QPushButton(LIGHTWalkingDialog);
        BTN_SUPPORT_TRANSITION_RDSP2RSSP->setObjectName(QStringLiteral("BTN_SUPPORT_TRANSITION_RDSP2RSSP"));
        BTN_SUPPORT_TRANSITION_RDSP2RSSP->setGeometry(QRect(583, 640, 70, 21));
        QFont font2;
        font2.setPointSize(7);
        BTN_SUPPORT_TRANSITION_RDSP2RSSP->setFont(font2);
        BTN_SUPPORT_TRANSITION_RDSP2LDSP = new QPushButton(LIGHTWalkingDialog);
        BTN_SUPPORT_TRANSITION_RDSP2LDSP->setObjectName(QStringLiteral("BTN_SUPPORT_TRANSITION_RDSP2LDSP"));
        BTN_SUPPORT_TRANSITION_RDSP2LDSP->setEnabled(false);
        BTN_SUPPORT_TRANSITION_RDSP2LDSP->setGeometry(QRect(583, 670, 70, 21));
        BTN_SUPPORT_TRANSITION_RDSP2LDSP->setFont(font2);
        BTN_SUPPORT_TRANSITION_LDSP2LSSP = new QPushButton(LIGHTWalkingDialog);
        BTN_SUPPORT_TRANSITION_LDSP2LSSP->setObjectName(QStringLiteral("BTN_SUPPORT_TRANSITION_LDSP2LSSP"));
        BTN_SUPPORT_TRANSITION_LDSP2LSSP->setGeometry(QRect(583, 700, 70, 21));
        BTN_SUPPORT_TRANSITION_LDSP2LSSP->setFont(font2);
        BTN_SUPPORT_TRANSITION_LSSP2LDSP = new QPushButton(LIGHTWalkingDialog);
        BTN_SUPPORT_TRANSITION_LSSP2LDSP->setObjectName(QStringLiteral("BTN_SUPPORT_TRANSITION_LSSP2LDSP"));
        BTN_SUPPORT_TRANSITION_LSSP2LDSP->setGeometry(QRect(663, 700, 70, 21));
        BTN_SUPPORT_TRANSITION_LSSP2LDSP->setFont(font2);
        BTN_SUPPORT_TRANSITION_RSSP2RDSP = new QPushButton(LIGHTWalkingDialog);
        BTN_SUPPORT_TRANSITION_RSSP2RDSP->setObjectName(QStringLiteral("BTN_SUPPORT_TRANSITION_RSSP2RDSP"));
        BTN_SUPPORT_TRANSITION_RSSP2RDSP->setGeometry(QRect(663, 640, 70, 21));
        BTN_SUPPORT_TRANSITION_RSSP2RDSP->setFont(font2);
        BTN_SUPPORT_TRANSITION_LDSP2RDSP = new QPushButton(LIGHTWalkingDialog);
        BTN_SUPPORT_TRANSITION_LDSP2RDSP->setObjectName(QStringLiteral("BTN_SUPPORT_TRANSITION_LDSP2RDSP"));
        BTN_SUPPORT_TRANSITION_LDSP2RDSP->setEnabled(false);
        BTN_SUPPORT_TRANSITION_LDSP2RDSP->setGeometry(QRect(663, 670, 70, 21));
        BTN_SUPPORT_TRANSITION_LDSP2RDSP->setFont(font2);
        frame = new QFrame(LIGHTWalkingDialog);
        frame->setObjectName(QStringLiteral("frame"));
        frame->setGeometry(QRect(20, 430, 180, 181));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        BTN_SYSID_COMREF2ZMP_SSP_LF_X = new QPushButton(frame);
        BTN_SYSID_COMREF2ZMP_SSP_LF_X->setObjectName(QStringLiteral("BTN_SYSID_COMREF2ZMP_SSP_LF_X"));
        BTN_SYSID_COMREF2ZMP_SSP_LF_X->setGeometry(QRect(96, 130, 70, 18));
        BTN_SYSID_COMREF2ZMP_SSP_LF_X->setFont(font2);
        BTN_SYSID_COMREF2ZMP_DSP_LF_Y = new QPushButton(frame);
        BTN_SYSID_COMREF2ZMP_DSP_LF_Y->setObjectName(QStringLiteral("BTN_SYSID_COMREF2ZMP_DSP_LF_Y"));
        BTN_SYSID_COMREF2ZMP_DSP_LF_Y->setGeometry(QRect(96, 106, 70, 18));
        BTN_SYSID_COMREF2ZMP_DSP_LF_Y->setFont(font2);
        label_63 = new QLabel(frame);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(7, 31, 60, 20));
        QFont font3;
        font3.setPointSize(8);
        label_63->setFont(font3);
        label_63->setAlignment(Qt::AlignCenter);
        CON_SYSID_COMREF2ZMP_DFREQ = new QLineEdit(frame);
        CON_SYSID_COMREF2ZMP_DFREQ->setObjectName(QStringLiteral("CON_SYSID_COMREF2ZMP_DFREQ"));
        CON_SYSID_COMREF2ZMP_DFREQ->setGeometry(QRect(121, 51, 45, 23));
        CON_SYSID_COMREF2ZMP_DFREQ->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_62 = new QLabel(frame);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(0, 10, 181, 16));
        label_62->setFont(font3);
        label_62->setAlignment(Qt::AlignCenter);
        CON_SYSID_COMREF2ZMP_NUM = new QLineEdit(frame);
        CON_SYSID_COMREF2ZMP_NUM->setObjectName(QStringLiteral("CON_SYSID_COMREF2ZMP_NUM"));
        CON_SYSID_COMREF2ZMP_NUM->setGeometry(QRect(69, 51, 45, 23));
        CON_SYSID_COMREF2ZMP_NUM->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        BTN_SYSID_COMREF2ZMP_DSP_RF_Y = new QPushButton(frame);
        BTN_SYSID_COMREF2ZMP_DSP_RF_Y->setObjectName(QStringLiteral("BTN_SYSID_COMREF2ZMP_DSP_RF_Y"));
        BTN_SYSID_COMREF2ZMP_DSP_RF_Y->setGeometry(QRect(20, 106, 70, 18));
        BTN_SYSID_COMREF2ZMP_DSP_RF_Y->setFont(font2);
        BTN_SYSID_COMREF2ZMP_SSP_RF_X = new QPushButton(frame);
        BTN_SYSID_COMREF2ZMP_SSP_RF_X->setObjectName(QStringLiteral("BTN_SYSID_COMREF2ZMP_SSP_RF_X"));
        BTN_SYSID_COMREF2ZMP_SSP_RF_X->setGeometry(QRect(20, 130, 70, 18));
        BTN_SYSID_COMREF2ZMP_SSP_RF_X->setFont(font2);
        BTN_SYSID_COMREF2ZMP_DSP_LF_X = new QPushButton(frame);
        BTN_SYSID_COMREF2ZMP_DSP_LF_X->setObjectName(QStringLiteral("BTN_SYSID_COMREF2ZMP_DSP_LF_X"));
        BTN_SYSID_COMREF2ZMP_DSP_LF_X->setGeometry(QRect(96, 82, 70, 18));
        BTN_SYSID_COMREF2ZMP_DSP_LF_X->setFont(font2);
        label_66 = new QLabel(frame);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(114, 31, 60, 20));
        label_66->setFont(font3);
        label_66->setAlignment(Qt::AlignCenter);
        CON_SYSID_COMREF2ZMP_COMMAG = new QLineEdit(frame);
        CON_SYSID_COMREF2ZMP_COMMAG->setObjectName(QStringLiteral("CON_SYSID_COMREF2ZMP_COMMAG"));
        CON_SYSID_COMREF2ZMP_COMMAG->setGeometry(QRect(17, 51, 45, 23));
        CON_SYSID_COMREF2ZMP_COMMAG->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        BTN_SYSID_COMREF2ZMP_DSP_RF_X = new QPushButton(frame);
        BTN_SYSID_COMREF2ZMP_DSP_RF_X->setObjectName(QStringLiteral("BTN_SYSID_COMREF2ZMP_DSP_RF_X"));
        BTN_SYSID_COMREF2ZMP_DSP_RF_X->setGeometry(QRect(20, 82, 70, 18));
        BTN_SYSID_COMREF2ZMP_DSP_RF_X->setFont(font2);
        label_64 = new QLabel(frame);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(61, 31, 60, 20));
        label_64->setFont(font3);
        label_64->setAlignment(Qt::AlignCenter);
        BTN_SYSID_COMREF2ZMP_SSP_RF_Y = new QPushButton(frame);
        BTN_SYSID_COMREF2ZMP_SSP_RF_Y->setObjectName(QStringLiteral("BTN_SYSID_COMREF2ZMP_SSP_RF_Y"));
        BTN_SYSID_COMREF2ZMP_SSP_RF_Y->setGeometry(QRect(20, 154, 70, 18));
        BTN_SYSID_COMREF2ZMP_SSP_RF_Y->setFont(font2);
        BTN_SYSID_COMREF2ZMP_SSP_LF_Y = new QPushButton(frame);
        BTN_SYSID_COMREF2ZMP_SSP_LF_Y->setObjectName(QStringLiteral("BTN_SYSID_COMREF2ZMP_SSP_LF_Y"));
        BTN_SYSID_COMREF2ZMP_SSP_LF_Y->setGeometry(QRect(96, 154, 70, 18));
        BTN_SYSID_COMREF2ZMP_SSP_LF_Y->setFont(font2);
        CON_COMMOVE_SSP_TIME = new QLineEdit(LIGHTWalkingDialog);
        CON_COMMOVE_SSP_TIME->setObjectName(QStringLiteral("CON_COMMOVE_SSP_TIME"));
        CON_COMMOVE_SSP_TIME->setGeometry(QRect(618, 504, 40, 23));
        CON_COMMOVE_SSP_TIME->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        BTN_COMMOVE_SSP_GO = new QPushButton(LIGHTWalkingDialog);
        BTN_COMMOVE_SSP_GO->setObjectName(QStringLiteral("BTN_COMMOVE_SSP_GO"));
        BTN_COMMOVE_SSP_GO->setGeometry(QRect(670, 479, 61, 41));
        label_26 = new QLabel(LIGHTWalkingDialog);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(528, 396, 201, 16));
        label_26->setAlignment(Qt::AlignCenter);
        label_30 = new QLabel(LIGHTWalkingDialog);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(573, 507, 41, 16));
        label_30->setFont(font2);
        label_30->setAlignment(Qt::AlignCenter);
        label_31 = new QLabel(LIGHTWalkingDialog);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(538, 426, 81, 16));
        label_31->setFont(font2);
        label_31->setAlignment(Qt::AlignCenter);
        CON_COMMOVE_SSP_SWING_X = new QLineEdit(LIGHTWalkingDialog);
        CON_COMMOVE_SSP_SWING_X->setObjectName(QStringLiteral("CON_COMMOVE_SSP_SWING_X"));
        CON_COMMOVE_SSP_SWING_X->setGeometry(QRect(618, 423, 40, 23));
        CON_COMMOVE_SSP_SWING_X->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        CON_COMMOVE_SSP_SWING_Y = new QLineEdit(LIGHTWalkingDialog);
        CON_COMMOVE_SSP_SWING_Y->setObjectName(QStringLiteral("CON_COMMOVE_SSP_SWING_Y"));
        CON_COMMOVE_SSP_SWING_Y->setGeometry(QRect(618, 450, 40, 23));
        CON_COMMOVE_SSP_SWING_Y->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_34 = new QLabel(LIGHTWalkingDialog);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(538, 453, 81, 16));
        label_34->setFont(font2);
        label_34->setAlignment(Qt::AlignCenter);
        CON_COMMOVE_SSP_SWING_Z = new QLineEdit(LIGHTWalkingDialog);
        CON_COMMOVE_SSP_SWING_Z->setObjectName(QStringLiteral("CON_COMMOVE_SSP_SWING_Z"));
        CON_COMMOVE_SSP_SWING_Z->setGeometry(QRect(618, 477, 40, 23));
        CON_COMMOVE_SSP_SWING_Z->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_35 = new QLabel(LIGHTWalkingDialog);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(538, 480, 81, 16));
        label_35->setFont(font2);
        label_35->setAlignment(Qt::AlignCenter);
        frame_2 = new QFrame(LIGHTWalkingDialog);
        frame_2->setObjectName(QStringLiteral("frame_2"));
        frame_2->setGeometry(QRect(670, 420, 61, 51));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        RBTN_COM_SSP_REFFRAME_RF = new QRadioButton(frame_2);
        RBTN_COM_SSP_REFFRAME_RF->setObjectName(QStringLiteral("RBTN_COM_SSP_REFFRAME_RF"));
        RBTN_COM_SSP_REFFRAME_RF->setGeometry(QRect(10, 3, 61, 21));
        RBTN_COM_SSP_REFFRAME_RF->setChecked(true);
        RBTN_COM_SSP_REFFRAME_LF = new QRadioButton(frame_2);
        RBTN_COM_SSP_REFFRAME_LF->setObjectName(QStringLiteral("RBTN_COM_SSP_REFFRAME_LF"));
        RBTN_COM_SSP_REFFRAME_LF->setGeometry(QRect(10, 26, 61, 21));
        RBTN_COM_SSP_REFFRAME_LF->setChecked(false);
        CON_SAVE_FILENAME = new QLineEdit(LIGHTWalkingDialog);
        CON_SAVE_FILENAME->setObjectName(QStringLiteral("CON_SAVE_FILENAME"));
        CON_SAVE_FILENAME->setGeometry(QRect(55, 290, 106, 31));
        CON_SAVE_FILENAME->setFont(font2);
        CON_SAVE_FILENAME->setAlignment(Qt::AlignCenter);
        CON_SAVE_FILENAME->setReadOnly(false);
        label_23 = new QLabel(LIGHTWalkingDialog);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(20, 300, 31, 16));
        QFont font4;
        font4.setPointSize(9);
        label_23->setFont(font4);
        label_23->setAlignment(Qt::AlignCenter);
        BTN_KINEMATIC_COMPENSATION_ON = new QPushButton(LIGHTWalkingDialog);
        BTN_KINEMATIC_COMPENSATION_ON->setObjectName(QStringLiteral("BTN_KINEMATIC_COMPENSATION_ON"));
        BTN_KINEMATIC_COMPENSATION_ON->setGeometry(QRect(570, 553, 80, 40));
        BTN_KINEMATIC_COMPENSATION_ON->setFont(font3);
        BTN_KINEMATIC_COMPENSATION_OFF = new QPushButton(LIGHTWalkingDialog);
        BTN_KINEMATIC_COMPENSATION_OFF->setObjectName(QStringLiteral("BTN_KINEMATIC_COMPENSATION_OFF"));
        BTN_KINEMATIC_COMPENSATION_OFF->setGeometry(QRect(660, 553, 80, 40));
        BTN_KINEMATIC_COMPENSATION_OFF->setFont(font3);
        BTN_SQUAT_GO = new QPushButton(LIGHTWalkingDialog);
        BTN_SQUAT_GO->setObjectName(QStringLiteral("BTN_SQUAT_GO"));
        BTN_SQUAT_GO->setGeometry(QRect(430, 633, 61, 41));
        CON_SQUAT_NUMBER = new QLineEdit(LIGHTWalkingDialog);
        CON_SQUAT_NUMBER->setObjectName(QStringLiteral("CON_SQUAT_NUMBER"));
        CON_SQUAT_NUMBER->setGeometry(QRect(380, 631, 40, 23));
        CON_SQUAT_NUMBER->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        frame_3 = new QFrame(LIGHTWalkingDialog);
        frame_3->setObjectName(QStringLiteral("frame_3"));
        frame_3->setGeometry(QRect(430, 574, 61, 51));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Raised);
        RBTN_SQUAT_MODE_DSP = new QRadioButton(frame_3);
        RBTN_SQUAT_MODE_DSP->setObjectName(QStringLiteral("RBTN_SQUAT_MODE_DSP"));
        RBTN_SQUAT_MODE_DSP->setGeometry(QRect(10, 3, 51, 21));
        RBTN_SQUAT_MODE_DSP->setChecked(true);
        RBTN_SQUAT_MODE_SSP = new QRadioButton(frame_3);
        RBTN_SQUAT_MODE_SSP->setObjectName(QStringLiteral("RBTN_SQUAT_MODE_SSP"));
        RBTN_SQUAT_MODE_SSP->setGeometry(QRect(10, 26, 51, 21));
        RBTN_SQUAT_MODE_SSP->setChecked(false);
        CON_SQUAT_PERIOD = new QLineEdit(LIGHTWalkingDialog);
        CON_SQUAT_PERIOD->setObjectName(QStringLiteral("CON_SQUAT_PERIOD"));
        CON_SQUAT_PERIOD->setGeometry(QRect(380, 604, 40, 23));
        CON_SQUAT_PERIOD->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        CON_SQUAT_HEIGHT = new QLineEdit(LIGHTWalkingDialog);
        CON_SQUAT_HEIGHT->setObjectName(QStringLiteral("CON_SQUAT_HEIGHT"));
        CON_SQUAT_HEIGHT->setGeometry(QRect(380, 577, 40, 23));
        CON_SQUAT_HEIGHT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_27 = new QLabel(LIGHTWalkingDialog);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(308, 550, 201, 16));
        label_27->setAlignment(Qt::AlignCenter);
        label_36 = new QLabel(LIGHTWalkingDialog);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(294, 607, 81, 16));
        label_36->setFont(font2);
        label_36->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_37 = new QLabel(LIGHTWalkingDialog);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(294, 634, 81, 16));
        label_37->setFont(font2);
        label_37->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_33 = new QLabel(LIGHTWalkingDialog);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(294, 580, 81, 16));
        label_33->setFont(font2);
        label_33->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        CON_AIRWALKING_STRIDE = new QLineEdit(LIGHTWalkingDialog);
        CON_AIRWALKING_STRIDE->setObjectName(QStringLiteral("CON_AIRWALKING_STRIDE"));
        CON_AIRWALKING_STRIDE->setGeometry(QRect(345, 433, 41, 23));
        CON_AIRWALKING_STRIDE->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_3 = new QLabel(LIGHTWalkingDialog);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(300, 435, 41, 20));
        label_3->setAlignment(Qt::AlignCenter);
        label_4 = new QLabel(LIGHTWalkingDialog);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(277, 463, 61, 20));
        CON_AIRWALKING_STEPTIME = new QLineEdit(LIGHTWalkingDialog);
        CON_AIRWALKING_STEPTIME->setObjectName(QStringLiteral("CON_AIRWALKING_STEPTIME"));
        CON_AIRWALKING_STEPTIME->setGeometry(QRect(345, 460, 41, 23));
        CON_AIRWALKING_STEPTIME->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_5 = new QLabel(LIGHTWalkingDialog);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(310, 490, 31, 16));
        BTN_AIRWALKING_GO = new QPushButton(LIGHTWalkingDialog);
        BTN_AIRWALKING_GO->setObjectName(QStringLiteral("BTN_AIRWALKING_GO"));
        BTN_AIRWALKING_GO->setGeometry(QRect(438, 446, 71, 61));
        label_7 = new QLabel(LIGHTWalkingDialog);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(390, 463, 31, 16));
        label_2 = new QLabel(LIGHTWalkingDialog);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(330, 408, 151, 16));
        label_2->setAlignment(Qt::AlignCenter);
        CON_AIRWALKING_NUM = new QLineEdit(LIGHTWalkingDialog);
        CON_AIRWALKING_NUM->setObjectName(QStringLiteral("CON_AIRWALKING_NUM"));
        CON_AIRWALKING_NUM->setGeometry(QRect(345, 487, 41, 23));
        CON_AIRWALKING_NUM->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_6 = new QLabel(LIGHTWalkingDialog);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(390, 435, 31, 16));
        label_8 = new QLabel(LIGHTWalkingDialog);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(390, 490, 41, 16));

        retranslateUi(LIGHTWalkingDialog);

        QMetaObject::connectSlotsByName(LIGHTWalkingDialog);
    } // setupUi

    void retranslateUi(QWidget *LIGHTWalkingDialog)
    {
        LIGHTWalkingDialog->setWindowTitle(QApplication::translate("LIGHTWalkingDialog", "Form", Q_NULLPTR));
        label->setText(QApplication::translate("LIGHTWalkingDialog", "LIGHT Walking Dialog Page 1", Q_NULLPTR));
        BTN_JOINTSPACE_MOVE_GO->setText(QApplication::translate("LIGHTWalkingDialog", "Go to \n"
"Zero Pose", Q_NULLPTR));
        BTN_WORKSPACE_MOVE_GO->setText(QApplication::translate("LIGHTWalkingDialog", "Go", Q_NULLPTR));
        label_10->setText(QApplication::translate("LIGHTWalkingDialog", "<Work Space Moving Test>", Q_NULLPTR));
        groupBox->setTitle(QApplication::translate("LIGHTWalkingDialog", "[ Operation Target ]", Q_NULLPTR));
        RBTN_OPERATIONMODE_ROBOT->setText(QApplication::translate("LIGHTWalkingDialog", "Robot", Q_NULLPTR));
        RBTN_OPERATIONMODE_CHOREONOID->setText(QApplication::translate("LIGHTWalkingDialog", "Choreonoid", Q_NULLPTR));
        label_46->setText(QApplication::translate("LIGHTWalkingDialog", "Current Mode : ", Q_NULLPTR));
        LE_ROBOT_OR_SIM->setText(QString());
        CON_WORKSPACE_RIGHT_X->setText(QApplication::translate("LIGHTWalkingDialog", "0.04", Q_NULLPTR));
        CON_WORKSPACE_RIGHT_Z->setText(QApplication::translate("LIGHTWalkingDialog", "-0.70", Q_NULLPTR));
        CON_WORKSPACE_RIGHT_Y->setText(QApplication::translate("LIGHTWalkingDialog", "-0.11", Q_NULLPTR));
        label_11->setText(QApplication::translate("LIGHTWalkingDialog", "(Right)", Q_NULLPTR));
        label_12->setText(QApplication::translate("LIGHTWalkingDialog", "(Left)", Q_NULLPTR));
        CON_WORKSPACE_LEFT_Y->setText(QApplication::translate("LIGHTWalkingDialog", "0.11", Q_NULLPTR));
        CON_WORKSPACE_LEFT_X->setText(QApplication::translate("LIGHTWalkingDialog", "0.04", Q_NULLPTR));
        CON_WORKSPACE_LEFT_Z->setText(QApplication::translate("LIGHTWalkingDialog", "-0.70", Q_NULLPTR));
        label_13->setText(QApplication::translate("LIGHTWalkingDialog", "X pos", Q_NULLPTR));
        label_14->setText(QApplication::translate("LIGHTWalkingDialog", "Y pos", Q_NULLPTR));
        label_15->setText(QApplication::translate("LIGHTWalkingDialog", "Z pos", Q_NULLPTR));
        label_16->setText(QApplication::translate("LIGHTWalkingDialog", "Time", Q_NULLPTR));
        CON_WORKSPACE_TIME->setText(QApplication::translate("LIGHTWalkingDialog", "3.0", Q_NULLPTR));
        label_17->setText(QApplication::translate("LIGHTWalkingDialog", "sec", Q_NULLPTR));
        label_18->setText(QApplication::translate("LIGHTWalkingDialog", "<CoM Moving in DSP>", Q_NULLPTR));
        label_25->setText(QApplication::translate("LIGHTWalkingDialog", "Time", Q_NULLPTR));
        label_20->setText(QApplication::translate("LIGHTWalkingDialog", "sec", Q_NULLPTR));
        CON_COMMOVE_Z->setText(QApplication::translate("LIGHTWalkingDialog", "0.70", Q_NULLPTR));
        CON_COMMOVE_X->setText(QApplication::translate("LIGHTWalkingDialog", "0.00", Q_NULLPTR));
        label_22->setText(QApplication::translate("LIGHTWalkingDialog", "Base Height", Q_NULLPTR));
        CON_COMMOVE_Y->setText(QApplication::translate("LIGHTWalkingDialog", "0.00", Q_NULLPTR));
        label_19->setText(QApplication::translate("LIGHTWalkingDialog", "X pos", Q_NULLPTR));
        CON_COMMOVE_TIME->setText(QApplication::translate("LIGHTWalkingDialog", "3.0", Q_NULLPTR));
        BTN_COMMOVE_GO->setText(QApplication::translate("LIGHTWalkingDialog", "Go", Q_NULLPTR));
        label_21->setText(QApplication::translate("LIGHTWalkingDialog", "Y pos", Q_NULLPTR));
        BTN_SAVE_START->setText(QApplication::translate("LIGHTWalkingDialog", "Save Start", Q_NULLPTR));
        BTN_SAVE_END->setText(QApplication::translate("LIGHTWalkingDialog", "Save End", Q_NULLPTR));
        CON_COMMOVE_PELVIS_PITCH->setText(QApplication::translate("LIGHTWalkingDialog", "0", Q_NULLPTR));
        label_38->setText(QApplication::translate("LIGHTWalkingDialog", "Pelvis Pitch", Q_NULLPTR));
        label_39->setText(QApplication::translate("LIGHTWalkingDialog", "deg", Q_NULLPTR));
        groupBox_4->setTitle(QApplication::translate("LIGHTWalkingDialog", "[ Robot(LIGHT) Control Mode ]", Q_NULLPTR));
        BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_POS->setText(QApplication::translate("LIGHTWalkingDialog", "ALL Joint Change to Pos. Ctrl.", Q_NULLPTR));
        CBX_ROBOT_CONTROLMETHOD_RHY->setText(QApplication::translate("LIGHTWalkingDialog", "RHY", Q_NULLPTR));
        CBX_ROBOT_CONTROLMETHOD_RHR->setText(QApplication::translate("LIGHTWalkingDialog", "RHR", Q_NULLPTR));
        CBX_ROBOT_CONTROLMETHOD_RHP->setText(QApplication::translate("LIGHTWalkingDialog", "RHP", Q_NULLPTR));
        CBX_ROBOT_CONTROLMETHOD_RKN->setText(QApplication::translate("LIGHTWalkingDialog", "RKN", Q_NULLPTR));
        CBX_ROBOT_CONTROLMETHOD_RANK->setText(QApplication::translate("LIGHTWalkingDialog", "RANK(Both)", Q_NULLPTR));
        CBX_ROBOT_CONTROLMETHOD_LHY->setText(QApplication::translate("LIGHTWalkingDialog", "LHY", Q_NULLPTR));
        CBX_ROBOT_CONTROLMETHOD_LANK->setText(QApplication::translate("LIGHTWalkingDialog", "LANK(Both)", Q_NULLPTR));
        CBX_ROBOT_CONTROLMETHOD_LHP->setText(QApplication::translate("LIGHTWalkingDialog", "LHP", Q_NULLPTR));
        CBX_ROBOT_CONTROLMETHOD_LHR->setText(QApplication::translate("LIGHTWalkingDialog", "LHR", Q_NULLPTR));
        CBX_ROBOT_CONTROLMETHOD_LKN->setText(QApplication::translate("LIGHTWalkingDialog", "LKN", Q_NULLPTR));
        BTN_ROBOT_CONTROLMETHOD_CHANGE->setText(QApplication::translate("LIGHTWalkingDialog", "Mode Change", Q_NULLPTR));
        BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_TOR->setText(QApplication::translate("LIGHTWalkingDialog", "ALL Joint Change to Tor. Ctrl.", Q_NULLPTR));
        label_42->setText(QApplication::translate("LIGHTWalkingDialog", "(Checked : Position Control, Unchecked : Torque Control)", Q_NULLPTR));
        groupBox_3->setTitle(QApplication::translate("LIGHTWalkingDialog", "[IMU Handling]", Q_NULLPTR));
        BTN_IMU_NULL->setText(QApplication::translate("LIGHTWalkingDialog", "Nulling", Q_NULLPTR));
        LE_IMU_ROLL->setText(QString());
        label_43->setText(QApplication::translate("LIGHTWalkingDialog", "R", Q_NULLPTR));
        label_44->setText(QApplication::translate("LIGHTWalkingDialog", "P", Q_NULLPTR));
        label_45->setText(QApplication::translate("LIGHTWalkingDialog", "Y", Q_NULLPTR));
        BTN_IMU_RESET->setText(QApplication::translate("LIGHTWalkingDialog", "Reset", Q_NULLPTR));
        BTN_IMU_ENABLE->setText(QApplication::translate("LIGHTWalkingDialog", "Enable", Q_NULLPTR));
        BTN_IMU_DISABLE->setText(QApplication::translate("LIGHTWalkingDialog", "Disable", Q_NULLPTR));
        LE_IMU_PITCH->setText(QString());
        LE_IMU_YAW->setText(QString());
        groupBox_2->setTitle(QString());
        RBTN_COM_REFFRAME_LF->setText(QApplication::translate("LIGHTWalkingDialog", "LF", Q_NULLPTR));
        RBTN_COM_REFFRAME_RF->setText(QApplication::translate("LIGHTWalkingDialog", "RF", Q_NULLPTR));
        label_29->setText(QApplication::translate("LIGHTWalkingDialog", "<SupportTransition>", Q_NULLPTR));
        BTN_SUPPORT_TRANSITION_RDSP2RSSP->setText(QApplication::translate("LIGHTWalkingDialog", "RDSP > RSSP", Q_NULLPTR));
        BTN_SUPPORT_TRANSITION_RDSP2LDSP->setText(QApplication::translate("LIGHTWalkingDialog", "RDSP > LDSP", Q_NULLPTR));
        BTN_SUPPORT_TRANSITION_LDSP2LSSP->setText(QApplication::translate("LIGHTWalkingDialog", "LDSP > LSSP", Q_NULLPTR));
        BTN_SUPPORT_TRANSITION_LSSP2LDSP->setText(QApplication::translate("LIGHTWalkingDialog", "LSSP > LDSP", Q_NULLPTR));
        BTN_SUPPORT_TRANSITION_RSSP2RDSP->setText(QApplication::translate("LIGHTWalkingDialog", "RSSP > RDSP", Q_NULLPTR));
        BTN_SUPPORT_TRANSITION_LDSP2RDSP->setText(QApplication::translate("LIGHTWalkingDialog", "LDSP > RDSP", Q_NULLPTR));
        BTN_SYSID_COMREF2ZMP_SSP_LF_X->setText(QApplication::translate("LIGHTWalkingDialog", "SSP LF X", Q_NULLPTR));
        BTN_SYSID_COMREF2ZMP_DSP_LF_Y->setText(QApplication::translate("LIGHTWalkingDialog", "DSP LF Y", Q_NULLPTR));
        label_63->setText(QApplication::translate("LIGHTWalkingDialog", "CoM Mag", Q_NULLPTR));
        CON_SYSID_COMREF2ZMP_DFREQ->setText(QApplication::translate("LIGHTWalkingDialog", "1.05", Q_NULLPTR));
        label_62->setText(QApplication::translate("LIGHTWalkingDialog", "<CoMREF to ZMP System ID>", Q_NULLPTR));
        CON_SYSID_COMREF2ZMP_NUM->setText(QApplication::translate("LIGHTWalkingDialog", "3.0", Q_NULLPTR));
        BTN_SYSID_COMREF2ZMP_DSP_RF_Y->setText(QApplication::translate("LIGHTWalkingDialog", "DSP RF Y", Q_NULLPTR));
        BTN_SYSID_COMREF2ZMP_SSP_RF_X->setText(QApplication::translate("LIGHTWalkingDialog", "SSP RF X", Q_NULLPTR));
        BTN_SYSID_COMREF2ZMP_DSP_LF_X->setText(QApplication::translate("LIGHTWalkingDialog", "DSP LF X", Q_NULLPTR));
        label_66->setText(QApplication::translate("LIGHTWalkingDialog", "dFreq", Q_NULLPTR));
        CON_SYSID_COMREF2ZMP_COMMAG->setText(QApplication::translate("LIGHTWalkingDialog", "0.005", Q_NULLPTR));
        BTN_SYSID_COMREF2ZMP_DSP_RF_X->setText(QApplication::translate("LIGHTWalkingDialog", "DSP RF X", Q_NULLPTR));
        label_64->setText(QApplication::translate("LIGHTWalkingDialog", "Max. Freq", Q_NULLPTR));
        BTN_SYSID_COMREF2ZMP_SSP_RF_Y->setText(QApplication::translate("LIGHTWalkingDialog", "SSP RF Y", Q_NULLPTR));
        BTN_SYSID_COMREF2ZMP_SSP_LF_Y->setText(QApplication::translate("LIGHTWalkingDialog", "SSP LF Y", Q_NULLPTR));
        CON_COMMOVE_SSP_TIME->setText(QApplication::translate("LIGHTWalkingDialog", "3.0", Q_NULLPTR));
        BTN_COMMOVE_SSP_GO->setText(QApplication::translate("LIGHTWalkingDialog", "Go", Q_NULLPTR));
        label_26->setText(QApplication::translate("LIGHTWalkingDialog", "<CoM Moving in SSP>", Q_NULLPTR));
        label_30->setText(QApplication::translate("LIGHTWalkingDialog", "Time [s]", Q_NULLPTR));
        label_31->setText(QApplication::translate("LIGHTWalkingDialog", "Swing X pos[m]", Q_NULLPTR));
        CON_COMMOVE_SSP_SWING_X->setText(QApplication::translate("LIGHTWalkingDialog", "0.00", Q_NULLPTR));
        CON_COMMOVE_SSP_SWING_Y->setText(QApplication::translate("LIGHTWalkingDialog", "0.31", Q_NULLPTR));
        label_34->setText(QApplication::translate("LIGHTWalkingDialog", "Swing Y pos[m]", Q_NULLPTR));
        CON_COMMOVE_SSP_SWING_Z->setText(QApplication::translate("LIGHTWalkingDialog", "0.05", Q_NULLPTR));
        label_35->setText(QApplication::translate("LIGHTWalkingDialog", "Swing Z pos[m]", Q_NULLPTR));
        RBTN_COM_SSP_REFFRAME_RF->setText(QApplication::translate("LIGHTWalkingDialog", "RF", Q_NULLPTR));
        RBTN_COM_SSP_REFFRAME_LF->setText(QApplication::translate("LIGHTWalkingDialog", "LF", Q_NULLPTR));
        CON_SAVE_FILENAME->setText(QString());
        label_23->setText(QApplication::translate("LIGHTWalkingDialog", "Title", Q_NULLPTR));
        BTN_KINEMATIC_COMPENSATION_ON->setText(QApplication::translate("LIGHTWalkingDialog", "Kinematic\n"
"Comp. On", Q_NULLPTR));
        BTN_KINEMATIC_COMPENSATION_OFF->setText(QApplication::translate("LIGHTWalkingDialog", "Kinematic\n"
"Comp. Off", Q_NULLPTR));
        BTN_SQUAT_GO->setText(QApplication::translate("LIGHTWalkingDialog", "Go", Q_NULLPTR));
        CON_SQUAT_NUMBER->setText(QApplication::translate("LIGHTWalkingDialog", "5", Q_NULLPTR));
        RBTN_SQUAT_MODE_DSP->setText(QApplication::translate("LIGHTWalkingDialog", "DSP", Q_NULLPTR));
        RBTN_SQUAT_MODE_SSP->setText(QApplication::translate("LIGHTWalkingDialog", "SSP", Q_NULLPTR));
        CON_SQUAT_PERIOD->setText(QApplication::translate("LIGHTWalkingDialog", "2.50", Q_NULLPTR));
        CON_SQUAT_HEIGHT->setText(QApplication::translate("LIGHTWalkingDialog", "0.12", Q_NULLPTR));
        label_27->setText(QApplication::translate("LIGHTWalkingDialog", "<Squat Motion>", Q_NULLPTR));
        label_36->setText(QApplication::translate("LIGHTWalkingDialog", "Period [sec]", Q_NULLPTR));
        label_37->setText(QApplication::translate("LIGHTWalkingDialog", " Number [times]", Q_NULLPTR));
        label_33->setText(QApplication::translate("LIGHTWalkingDialog", " Down Height [m]", Q_NULLPTR));
        CON_AIRWALKING_STRIDE->setText(QApplication::translate("LIGHTWalkingDialog", "0.25", Q_NULLPTR));
        label_3->setText(QApplication::translate("LIGHTWalkingDialog", "Stride", Q_NULLPTR));
        label_4->setText(QApplication::translate("LIGHTWalkingDialog", "Step Time", Q_NULLPTR));
        CON_AIRWALKING_STEPTIME->setText(QApplication::translate("LIGHTWalkingDialog", "0.90", Q_NULLPTR));
        label_5->setText(QApplication::translate("LIGHTWalkingDialog", "Num", Q_NULLPTR));
        BTN_AIRWALKING_GO->setText(QApplication::translate("LIGHTWalkingDialog", "Air\n"
"Walking\n"
"Go", Q_NULLPTR));
        label_7->setText(QApplication::translate("LIGHTWalkingDialog", "sec", Q_NULLPTR));
        label_2->setText(QApplication::translate("LIGHTWalkingDialog", "<Air Walking Motion>", Q_NULLPTR));
        CON_AIRWALKING_NUM->setText(QApplication::translate("LIGHTWalkingDialog", "10", Q_NULLPTR));
        label_6->setText(QApplication::translate("LIGHTWalkingDialog", "m", Q_NULLPTR));
        label_8->setText(QApplication::translate("LIGHTWalkingDialog", "steps", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class LIGHTWalkingDialog: public Ui_LIGHTWalkingDialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_LIGHTWALKINGDIALOG_H
