/********************************************************************************
** Form generated from reading UI file 'LIGHTWalkingDialog2.ui'
**
** Created by: Qt User Interface Compiler version 5.9.8
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_LIGHTWALKINGDIALOG2_H
#define UI_LIGHTWALKINGDIALOG2_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QGraphicsView>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>

QT_BEGIN_NAMESPACE

class Ui_LIGHTWalkingDialog2
{
public:
    QGroupBox *groupBox;
    QRadioButton *RBTN_OPERATIONMODE_ROBOT;
    QRadioButton *RBTN_OPERATIONMODE_CHOREONOID;
    QLabel *label_46;
    QLineEdit *LE_ROBOT_OR_SIM;
    QGroupBox *groupBox_4;
    QPushButton *BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_POS;
    QCheckBox *CBX_ROBOT_CONTROLMETHOD_RHY;
    QCheckBox *CBX_ROBOT_CONTROLMETHOD_RHR;
    QCheckBox *CBX_ROBOT_CONTROLMETHOD_RHP;
    QCheckBox *CBX_ROBOT_CONTROLMETHOD_RKN;
    QCheckBox *CBX_ROBOT_CONTROLMETHOD_RANK;
    QCheckBox *CBX_ROBOT_CONTROLMETHOD_LHY;
    QCheckBox *CBX_ROBOT_CONTROLMETHOD_LANK;
    QCheckBox *CBX_ROBOT_CONTROLMETHOD_LHP;
    QCheckBox *CBX_ROBOT_CONTROLMETHOD_LHR;
    QCheckBox *CBX_ROBOT_CONTROLMETHOD_LKN;
    QPushButton *BTN_ROBOT_CONTROLMETHOD_CHANGE;
    QPushButton *BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_TOR;
    QLabel *label_42;
    QGroupBox *groupBox_3;
    QPushButton *BTN_IMU_NULL;
    QLineEdit *LE_IMU_ROLL;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QPushButton *BTN_IMU_RESET;
    QPushButton *BTN_IMU_ENABLE;
    QPushButton *BTN_IMU_DISABLE;
    QLineEdit *LE_IMU_PITCH;
    QLineEdit *LE_IMU_YAW;
    QLabel *label;
    QPushButton *BTN_COM_SMOOTH_MOTION_GO;
    QLabel *label_52;
    QPushButton *BTN_RFSWINGUP_GO;
    QLabel *label_53;
    QPushButton *BTN_RFSWINGDOWN_GO;
    QPushButton *BTN_COM_SMOOTH_MOTION_GO_LDSP;
    QPushButton *BTN_LFSWINGDOWN_GO;
    QPushButton *BTN_LFSWINGUP_GO;
    QLabel *label_40;
    QLabel *label_54;
    QGroupBox *groupBox_5;
    QPushButton *BTN_JOYSTICK_ENABLE;
    QPushButton *BTN_JOYSTICK_DISABLE;
    QGraphicsView *LAMP_JOYSTICK;
    QLineEdit *LE_JOYSTICK_COMMAND_X;
    QLineEdit *LE_JOYSTICK_COMMAND_Y;
    QLineEdit *LE_JOYSTICK_COMMAND_YAW;
    QLabel *label_47;
    QLabel *label_48;
    QLabel *label_49;
    QLabel *label_58;
    QLabel *label_64;
    QLabel *label_59;
    QLabel *label_65;
    QLabel *label_57;
    QLabel *label_66;
    QLabel *label_67;
    QLabel *label_60;
    QLabel *label_61;
    QLabel *label_68;
    QLineEdit *CON_DYNAMICWALKING_STEP_NUMBER;
    QLabel *label_71;
    QLineEdit *CON_DYNAMICWALKING_YAW_ROTATION;
    QLabel *label_73;
    QLineEdit *CON_DYNAMICWALKING_SWAY_LENGTH;
    QLabel *label_55;
    QLabel *label_74;
    QLabel *label_75;
    QLabel *label_69;
    QLabel *label_56;
    QPushButton *BTN_DYNAMICWALKING_GO;
    QLabel *label_70;
    QLabel *label_63;
    QPushButton *BTN_DYNAMICWALKING_JOYSTICK_GO;
    QLineEdit *CON_DYNAMICWALKING_OFFSET_YAW;
    QLineEdit *CON_DYNAMICWALKING_DSP_TIME;
    QLabel *label_72;
    QLineEdit *CON_DYNAMICWALKING_Y_STEP;
    QLabel *label_76;
    QLineEdit *CON_DYNAMICWALKING_STEP_TIME;
    QLineEdit *CON_DYNAMICWALKING_X_STEP;
    QLineEdit *CON_DYNAMICWALKING_OFFSET_X;
    QLineEdit *CON_DYNAMICWALKING_OFFSET_Y;
    QLabel *label_62;
    QLabel *label_100;
    QLineEdit *CON_DYNAMICWALKING_STANCE_OFFSET;
    QLabel *label_101;
    QPushButton *BTN_SAVE_START;
    QPushButton *BTN_SAVE_END;
    QLineEdit *CON_SAVE_FILENAME;
    QLabel *label_23;

    void setupUi(QDialog *LIGHTWalkingDialog2)
    {
        if (LIGHTWalkingDialog2->objectName().isEmpty())
            LIGHTWalkingDialog2->setObjectName(QStringLiteral("LIGHTWalkingDialog2"));
        LIGHTWalkingDialog2->resize(780, 780);
        groupBox = new QGroupBox(LIGHTWalkingDialog2);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(20, 50, 211, 91));
        groupBox->setAlignment(Qt::AlignCenter);
        RBTN_OPERATIONMODE_ROBOT = new QRadioButton(groupBox);
        RBTN_OPERATIONMODE_ROBOT->setObjectName(QStringLiteral("RBTN_OPERATIONMODE_ROBOT"));
        RBTN_OPERATIONMODE_ROBOT->setGeometry(QRect(24, 30, 100, 21));
        RBTN_OPERATIONMODE_ROBOT->setChecked(true);
        RBTN_OPERATIONMODE_CHOREONOID = new QRadioButton(groupBox);
        RBTN_OPERATIONMODE_CHOREONOID->setObjectName(QStringLiteral("RBTN_OPERATIONMODE_CHOREONOID"));
        RBTN_OPERATIONMODE_CHOREONOID->setGeometry(QRect(94, 30, 100, 21));
        label_46 = new QLabel(groupBox);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(13, 62, 161, 16));
        label_46->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        LE_ROBOT_OR_SIM = new QLineEdit(groupBox);
        LE_ROBOT_OR_SIM->setObjectName(QStringLiteral("LE_ROBOT_OR_SIM"));
        LE_ROBOT_OR_SIM->setGeometry(QRect(110, 58, 91, 23));
        LE_ROBOT_OR_SIM->setAlignment(Qt::AlignCenter);
        LE_ROBOT_OR_SIM->setReadOnly(true);
        groupBox_4 = new QGroupBox(LIGHTWalkingDialog2);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(263, 52, 481, 151));
        groupBox_4->setAlignment(Qt::AlignCenter);
        BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_POS = new QPushButton(groupBox_4);
        BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_POS->setObjectName(QStringLiteral("BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_POS"));
        BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_POS->setGeometry(QRect(30, 110, 201, 31));
        CBX_ROBOT_CONTROLMETHOD_RHY = new QCheckBox(groupBox_4);
        CBX_ROBOT_CONTROLMETHOD_RHY->setObjectName(QStringLiteral("CBX_ROBOT_CONTROLMETHOD_RHY"));
        CBX_ROBOT_CONTROLMETHOD_RHY->setEnabled(false);
        CBX_ROBOT_CONTROLMETHOD_RHY->setGeometry(QRect(80, 30, 51, 20));
        CBX_ROBOT_CONTROLMETHOD_RHR = new QCheckBox(groupBox_4);
        CBX_ROBOT_CONTROLMETHOD_RHR->setObjectName(QStringLiteral("CBX_ROBOT_CONTROLMETHOD_RHR"));
        CBX_ROBOT_CONTROLMETHOD_RHR->setEnabled(true);
        CBX_ROBOT_CONTROLMETHOD_RHR->setGeometry(QRect(20, 30, 51, 20));
        CBX_ROBOT_CONTROLMETHOD_RHP = new QCheckBox(groupBox_4);
        CBX_ROBOT_CONTROLMETHOD_RHP->setObjectName(QStringLiteral("CBX_ROBOT_CONTROLMETHOD_RHP"));
        CBX_ROBOT_CONTROLMETHOD_RHP->setEnabled(true);
        CBX_ROBOT_CONTROLMETHOD_RHP->setGeometry(QRect(140, 30, 51, 20));
        CBX_ROBOT_CONTROLMETHOD_RKN = new QCheckBox(groupBox_4);
        CBX_ROBOT_CONTROLMETHOD_RKN->setObjectName(QStringLiteral("CBX_ROBOT_CONTROLMETHOD_RKN"));
        CBX_ROBOT_CONTROLMETHOD_RKN->setGeometry(QRect(200, 30, 51, 20));
        CBX_ROBOT_CONTROLMETHOD_RANK = new QCheckBox(groupBox_4);
        CBX_ROBOT_CONTROLMETHOD_RANK->setObjectName(QStringLiteral("CBX_ROBOT_CONTROLMETHOD_RANK"));
        CBX_ROBOT_CONTROLMETHOD_RANK->setGeometry(QRect(260, 30, 91, 20));
        CBX_ROBOT_CONTROLMETHOD_LHY = new QCheckBox(groupBox_4);
        CBX_ROBOT_CONTROLMETHOD_LHY->setObjectName(QStringLiteral("CBX_ROBOT_CONTROLMETHOD_LHY"));
        CBX_ROBOT_CONTROLMETHOD_LHY->setEnabled(false);
        CBX_ROBOT_CONTROLMETHOD_LHY->setGeometry(QRect(80, 60, 51, 20));
        CBX_ROBOT_CONTROLMETHOD_LANK = new QCheckBox(groupBox_4);
        CBX_ROBOT_CONTROLMETHOD_LANK->setObjectName(QStringLiteral("CBX_ROBOT_CONTROLMETHOD_LANK"));
        CBX_ROBOT_CONTROLMETHOD_LANK->setGeometry(QRect(260, 60, 91, 20));
        CBX_ROBOT_CONTROLMETHOD_LHP = new QCheckBox(groupBox_4);
        CBX_ROBOT_CONTROLMETHOD_LHP->setObjectName(QStringLiteral("CBX_ROBOT_CONTROLMETHOD_LHP"));
        CBX_ROBOT_CONTROLMETHOD_LHP->setEnabled(true);
        CBX_ROBOT_CONTROLMETHOD_LHP->setGeometry(QRect(140, 60, 51, 20));
        CBX_ROBOT_CONTROLMETHOD_LHR = new QCheckBox(groupBox_4);
        CBX_ROBOT_CONTROLMETHOD_LHR->setObjectName(QStringLiteral("CBX_ROBOT_CONTROLMETHOD_LHR"));
        CBX_ROBOT_CONTROLMETHOD_LHR->setEnabled(true);
        CBX_ROBOT_CONTROLMETHOD_LHR->setGeometry(QRect(20, 60, 51, 20));
        CBX_ROBOT_CONTROLMETHOD_LKN = new QCheckBox(groupBox_4);
        CBX_ROBOT_CONTROLMETHOD_LKN->setObjectName(QStringLiteral("CBX_ROBOT_CONTROLMETHOD_LKN"));
        CBX_ROBOT_CONTROLMETHOD_LKN->setGeometry(QRect(200, 60, 51, 20));
        BTN_ROBOT_CONTROLMETHOD_CHANGE = new QPushButton(groupBox_4);
        BTN_ROBOT_CONTROLMETHOD_CHANGE->setObjectName(QStringLiteral("BTN_ROBOT_CONTROLMETHOD_CHANGE"));
        BTN_ROBOT_CONTROLMETHOD_CHANGE->setGeometry(QRect(365, 35, 101, 41));
        BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_TOR = new QPushButton(groupBox_4);
        BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_TOR->setObjectName(QStringLiteral("BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_TOR"));
        BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_TOR->setGeometry(QRect(250, 110, 201, 31));
        label_42 = new QLabel(groupBox_4);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(50, 86, 381, 16));
        label_42->setAlignment(Qt::AlignCenter);
        groupBox_3 = new QGroupBox(LIGHTWalkingDialog2);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(21, 150, 211, 131));
        groupBox_3->setAlignment(Qt::AlignCenter);
        BTN_IMU_NULL = new QPushButton(groupBox_3);
        BTN_IMU_NULL->setObjectName(QStringLiteral("BTN_IMU_NULL"));
        BTN_IMU_NULL->setGeometry(QRect(110, 78, 91, 21));
        LE_IMU_ROLL = new QLineEdit(groupBox_3);
        LE_IMU_ROLL->setObjectName(QStringLiteral("LE_IMU_ROLL"));
        LE_IMU_ROLL->setGeometry(QRect(31, 34, 61, 23));
        LE_IMU_ROLL->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        LE_IMU_ROLL->setReadOnly(true);
        label_43 = new QLabel(groupBox_3);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(11, 38, 16, 16));
        label_43->setAlignment(Qt::AlignCenter);
        label_44 = new QLabel(groupBox_3);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(10, 70, 21, 16));
        label_44->setAlignment(Qt::AlignCenter);
        label_45 = new QLabel(groupBox_3);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(10, 100, 20, 20));
        label_45->setAlignment(Qt::AlignCenter);
        BTN_IMU_RESET = new QPushButton(groupBox_3);
        BTN_IMU_RESET->setObjectName(QStringLiteral("BTN_IMU_RESET"));
        BTN_IMU_RESET->setGeometry(QRect(110, 100, 91, 21));
        BTN_IMU_ENABLE = new QPushButton(groupBox_3);
        BTN_IMU_ENABLE->setObjectName(QStringLiteral("BTN_IMU_ENABLE"));
        BTN_IMU_ENABLE->setGeometry(QRect(110, 28, 91, 21));
        BTN_IMU_DISABLE = new QPushButton(groupBox_3);
        BTN_IMU_DISABLE->setObjectName(QStringLiteral("BTN_IMU_DISABLE"));
        BTN_IMU_DISABLE->setGeometry(QRect(110, 50, 91, 21));
        LE_IMU_PITCH = new QLineEdit(groupBox_3);
        LE_IMU_PITCH->setObjectName(QStringLiteral("LE_IMU_PITCH"));
        LE_IMU_PITCH->setGeometry(QRect(30, 66, 61, 23));
        LE_IMU_PITCH->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        LE_IMU_PITCH->setReadOnly(true);
        LE_IMU_YAW = new QLineEdit(groupBox_3);
        LE_IMU_YAW->setObjectName(QStringLiteral("LE_IMU_YAW"));
        LE_IMU_YAW->setGeometry(QRect(30, 98, 61, 23));
        LE_IMU_YAW->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        LE_IMU_YAW->setReadOnly(true);
        label = new QLabel(LIGHTWalkingDialog2);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(250, 10, 251, 31));
        QFont font;
        font.setPointSize(12);
        label->setFont(font);
        label->setAlignment(Qt::AlignCenter);
        BTN_COM_SMOOTH_MOTION_GO = new QPushButton(LIGHTWalkingDialog2);
        BTN_COM_SMOOTH_MOTION_GO->setObjectName(QStringLiteral("BTN_COM_SMOOTH_MOTION_GO"));
        BTN_COM_SMOOTH_MOTION_GO->setGeometry(QRect(280, 250, 91, 31));
        label_52 = new QLabel(LIGHTWalkingDialog2);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(280, 220, 191, 16));
        label_52->setAlignment(Qt::AlignCenter);
        BTN_RFSWINGUP_GO = new QPushButton(LIGHTWalkingDialog2);
        BTN_RFSWINGUP_GO->setObjectName(QStringLiteral("BTN_RFSWINGUP_GO"));
        BTN_RFSWINGUP_GO->setGeometry(QRect(504, 244, 91, 41));
        label_53 = new QLabel(LIGHTWalkingDialog2);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(539, 219, 151, 16));
        label_53->setAlignment(Qt::AlignCenter);
        BTN_RFSWINGDOWN_GO = new QPushButton(LIGHTWalkingDialog2);
        BTN_RFSWINGDOWN_GO->setObjectName(QStringLiteral("BTN_RFSWINGDOWN_GO"));
        BTN_RFSWINGDOWN_GO->setGeometry(QRect(635, 244, 91, 41));
        BTN_COM_SMOOTH_MOTION_GO_LDSP = new QPushButton(LIGHTWalkingDialog2);
        BTN_COM_SMOOTH_MOTION_GO_LDSP->setObjectName(QStringLiteral("BTN_COM_SMOOTH_MOTION_GO_LDSP"));
        BTN_COM_SMOOTH_MOTION_GO_LDSP->setGeometry(QRect(380, 250, 91, 31));
        BTN_LFSWINGDOWN_GO = new QPushButton(LIGHTWalkingDialog2);
        BTN_LFSWINGDOWN_GO->setObjectName(QStringLiteral("BTN_LFSWINGDOWN_GO"));
        BTN_LFSWINGDOWN_GO->setGeometry(QRect(635, 292, 91, 41));
        BTN_LFSWINGUP_GO = new QPushButton(LIGHTWalkingDialog2);
        BTN_LFSWINGUP_GO->setObjectName(QStringLiteral("BTN_LFSWINGUP_GO"));
        BTN_LFSWINGUP_GO->setGeometry(QRect(504, 292, 91, 41));
        label_40 = new QLabel(LIGHTWalkingDialog2);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(600, 255, 31, 20));
        label_40->setFont(font);
        label_40->setAlignment(Qt::AlignCenter);
        label_54 = new QLabel(LIGHTWalkingDialog2);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(600, 300, 31, 20));
        label_54->setFont(font);
        label_54->setAlignment(Qt::AlignCenter);
        groupBox_5 = new QGroupBox(LIGHTWalkingDialog2);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(20, 340, 721, 401));
        groupBox_5->setAlignment(Qt::AlignCenter);
        BTN_JOYSTICK_ENABLE = new QPushButton(groupBox_5);
        BTN_JOYSTICK_ENABLE->setObjectName(QStringLiteral("BTN_JOYSTICK_ENABLE"));
        BTN_JOYSTICK_ENABLE->setGeometry(QRect(470, 40, 71, 35));
        QFont font1;
        font1.setPointSize(8);
        BTN_JOYSTICK_ENABLE->setFont(font1);
        BTN_JOYSTICK_DISABLE = new QPushButton(groupBox_5);
        BTN_JOYSTICK_DISABLE->setObjectName(QStringLiteral("BTN_JOYSTICK_DISABLE"));
        BTN_JOYSTICK_DISABLE->setGeometry(QRect(550, 40, 71, 35));
        BTN_JOYSTICK_DISABLE->setFont(font1);
        LAMP_JOYSTICK = new QGraphicsView(groupBox_5);
        LAMP_JOYSTICK->setObjectName(QStringLiteral("LAMP_JOYSTICK"));
        LAMP_JOYSTICK->setGeometry(QRect(390, 46, 61, 21));
        LE_JOYSTICK_COMMAND_X = new QLineEdit(groupBox_5);
        LE_JOYSTICK_COMMAND_X->setObjectName(QStringLiteral("LE_JOYSTICK_COMMAND_X"));
        LE_JOYSTICK_COMMAND_X->setGeometry(QRect(488, 97, 61, 23));
        LE_JOYSTICK_COMMAND_X->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        LE_JOYSTICK_COMMAND_X->setReadOnly(true);
        LE_JOYSTICK_COMMAND_Y = new QLineEdit(groupBox_5);
        LE_JOYSTICK_COMMAND_Y->setObjectName(QStringLiteral("LE_JOYSTICK_COMMAND_Y"));
        LE_JOYSTICK_COMMAND_Y->setGeometry(QRect(488, 127, 61, 23));
        LE_JOYSTICK_COMMAND_Y->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        LE_JOYSTICK_COMMAND_Y->setReadOnly(true);
        LE_JOYSTICK_COMMAND_YAW = new QLineEdit(groupBox_5);
        LE_JOYSTICK_COMMAND_YAW->setObjectName(QStringLiteral("LE_JOYSTICK_COMMAND_YAW"));
        LE_JOYSTICK_COMMAND_YAW->setGeometry(QRect(488, 157, 61, 23));
        LE_JOYSTICK_COMMAND_YAW->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        LE_JOYSTICK_COMMAND_YAW->setReadOnly(true);
        label_47 = new QLabel(groupBox_5);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(390, 100, 101, 20));
        label_47->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_48 = new QLabel(groupBox_5);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(390, 130, 101, 20));
        label_48->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_49 = new QLabel(groupBox_5);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(390, 160, 101, 20));
        label_49->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_58 = new QLabel(groupBox_5);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(161, 74, 31, 16));
        label_64 = new QLabel(groupBox_5);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(161, 129, 21, 16));
        label_59 = new QLabel(groupBox_5);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(191, 100, 81, 20));
        label_65 = new QLabel(groupBox_5);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(48, 128, 51, 20));
        label_65->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_57 = new QLabel(groupBox_5);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(161, 201, 31, 16));
        label_66 = new QLabel(groupBox_5);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(161, 101, 31, 16));
        label_67 = new QLabel(groupBox_5);
        label_67->setObjectName(QStringLiteral("label_67"));
        label_67->setGeometry(QRect(39, 101, 61, 20));
        label_67->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_60 = new QLabel(groupBox_5);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(39, 74, 61, 20));
        label_61 = new QLabel(groupBox_5);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(332, 101, 41, 16));
        label_68 = new QLabel(groupBox_5);
        label_68->setObjectName(QStringLiteral("label_68"));
        label_68->setGeometry(QRect(331, 129, 21, 16));
        CON_DYNAMICWALKING_STEP_NUMBER = new QLineEdit(groupBox_5);
        CON_DYNAMICWALKING_STEP_NUMBER->setObjectName(QStringLiteral("CON_DYNAMICWALKING_STEP_NUMBER"));
        CON_DYNAMICWALKING_STEP_NUMBER->setGeometry(QRect(277, 98, 51, 23));
        CON_DYNAMICWALKING_STEP_NUMBER->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_71 = new QLabel(groupBox_5);
        label_71->setObjectName(QStringLiteral("label_71"));
        label_71->setGeometry(QRect(161, 230, 31, 16));
        CON_DYNAMICWALKING_YAW_ROTATION = new QLineEdit(groupBox_5);
        CON_DYNAMICWALKING_YAW_ROTATION->setObjectName(QStringLiteral("CON_DYNAMICWALKING_YAW_ROTATION"));
        CON_DYNAMICWALKING_YAW_ROTATION->setGeometry(QRect(106, 226, 51, 23));
        CON_DYNAMICWALKING_YAW_ROTATION->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_73 = new QLabel(groupBox_5);
        label_73->setObjectName(QStringLiteral("label_73"));
        label_73->setGeometry(QRect(199, 200, 71, 20));
        label_73->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        CON_DYNAMICWALKING_SWAY_LENGTH = new QLineEdit(groupBox_5);
        CON_DYNAMICWALKING_SWAY_LENGTH->setObjectName(QStringLiteral("CON_DYNAMICWALKING_SWAY_LENGTH"));
        CON_DYNAMICWALKING_SWAY_LENGTH->setGeometry(QRect(277, 71, 51, 23));
        CON_DYNAMICWALKING_SWAY_LENGTH->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_55 = new QLabel(groupBox_5);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(29, 200, 71, 20));
        label_55->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_74 = new QLabel(groupBox_5);
        label_74->setObjectName(QStringLiteral("label_74"));
        label_74->setGeometry(QRect(18, 155, 81, 20));
        label_74->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_75 = new QLabel(groupBox_5);
        label_75->setObjectName(QStringLiteral("label_75"));
        label_75->setGeometry(QRect(161, 156, 31, 16));
        label_69 = new QLabel(groupBox_5);
        label_69->setObjectName(QStringLiteral("label_69"));
        label_69->setGeometry(QRect(218, 128, 51, 20));
        label_69->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_56 = new QLabel(groupBox_5);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(79, 41, 201, 16));
        label_56->setAlignment(Qt::AlignCenter);
        BTN_DYNAMICWALKING_GO = new QPushButton(groupBox_5);
        BTN_DYNAMICWALKING_GO->setObjectName(QStringLiteral("BTN_DYNAMICWALKING_GO"));
        BTN_DYNAMICWALKING_GO->setGeometry(QRect(39, 270, 131, 51));
        label_70 = new QLabel(groupBox_5);
        label_70->setObjectName(QStringLiteral("label_70"));
        label_70->setGeometry(QRect(19, 228, 81, 20));
        label_70->setAlignment(Qt::AlignCenter);
        label_63 = new QLabel(groupBox_5);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(332, 73, 31, 16));
        BTN_DYNAMICWALKING_JOYSTICK_GO = new QPushButton(groupBox_5);
        BTN_DYNAMICWALKING_JOYSTICK_GO->setObjectName(QStringLiteral("BTN_DYNAMICWALKING_JOYSTICK_GO"));
        BTN_DYNAMICWALKING_JOYSTICK_GO->setGeometry(QRect(189, 270, 141, 51));
        CON_DYNAMICWALKING_OFFSET_YAW = new QLineEdit(groupBox_5);
        CON_DYNAMICWALKING_OFFSET_YAW->setObjectName(QStringLiteral("CON_DYNAMICWALKING_OFFSET_YAW"));
        CON_DYNAMICWALKING_OFFSET_YAW->setGeometry(QRect(106, 153, 51, 23));
        CON_DYNAMICWALKING_OFFSET_YAW->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        CON_DYNAMICWALKING_DSP_TIME = new QLineEdit(groupBox_5);
        CON_DYNAMICWALKING_DSP_TIME->setObjectName(QStringLiteral("CON_DYNAMICWALKING_DSP_TIME"));
        CON_DYNAMICWALKING_DSP_TIME->setGeometry(QRect(106, 98, 51, 23));
        CON_DYNAMICWALKING_DSP_TIME->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_72 = new QLabel(groupBox_5);
        label_72->setObjectName(QStringLiteral("label_72"));
        label_72->setGeometry(QRect(331, 202, 31, 16));
        CON_DYNAMICWALKING_Y_STEP = new QLineEdit(groupBox_5);
        CON_DYNAMICWALKING_Y_STEP->setObjectName(QStringLiteral("CON_DYNAMICWALKING_Y_STEP"));
        CON_DYNAMICWALKING_Y_STEP->setGeometry(QRect(276, 198, 51, 23));
        CON_DYNAMICWALKING_Y_STEP->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_76 = new QLabel(groupBox_5);
        label_76->setObjectName(QStringLiteral("label_76"));
        label_76->setGeometry(QRect(62, 320, 241, 71));
        label_76->setAlignment(Qt::AlignCenter);
        label_76->setIndent(-1);
        CON_DYNAMICWALKING_STEP_TIME = new QLineEdit(groupBox_5);
        CON_DYNAMICWALKING_STEP_TIME->setObjectName(QStringLiteral("CON_DYNAMICWALKING_STEP_TIME"));
        CON_DYNAMICWALKING_STEP_TIME->setGeometry(QRect(106, 71, 51, 23));
        CON_DYNAMICWALKING_STEP_TIME->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        CON_DYNAMICWALKING_X_STEP = new QLineEdit(groupBox_5);
        CON_DYNAMICWALKING_X_STEP->setObjectName(QStringLiteral("CON_DYNAMICWALKING_X_STEP"));
        CON_DYNAMICWALKING_X_STEP->setGeometry(QRect(106, 198, 51, 23));
        CON_DYNAMICWALKING_X_STEP->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        CON_DYNAMICWALKING_OFFSET_X = new QLineEdit(groupBox_5);
        CON_DYNAMICWALKING_OFFSET_X->setObjectName(QStringLiteral("CON_DYNAMICWALKING_OFFSET_X"));
        CON_DYNAMICWALKING_OFFSET_X->setGeometry(QRect(106, 126, 51, 23));
        CON_DYNAMICWALKING_OFFSET_X->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        CON_DYNAMICWALKING_OFFSET_Y = new QLineEdit(groupBox_5);
        CON_DYNAMICWALKING_OFFSET_Y->setObjectName(QStringLiteral("CON_DYNAMICWALKING_OFFSET_Y"));
        CON_DYNAMICWALKING_OFFSET_Y->setGeometry(QRect(276, 126, 51, 23));
        CON_DYNAMICWALKING_OFFSET_Y->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_62 = new QLabel(groupBox_5);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(192, 73, 81, 20));
        label_62->setAlignment(Qt::AlignCenter);
        label_100 = new QLabel(groupBox_5);
        label_100->setObjectName(QStringLiteral("label_100"));
        label_100->setGeometry(QRect(331, 232, 31, 16));
        CON_DYNAMICWALKING_STANCE_OFFSET = new QLineEdit(groupBox_5);
        CON_DYNAMICWALKING_STANCE_OFFSET->setObjectName(QStringLiteral("CON_DYNAMICWALKING_STANCE_OFFSET"));
        CON_DYNAMICWALKING_STANCE_OFFSET->setGeometry(QRect(276, 228, 51, 23));
        CON_DYNAMICWALKING_STANCE_OFFSET->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_101 = new QLabel(groupBox_5);
        label_101->setObjectName(QStringLiteral("label_101"));
        label_101->setGeometry(QRect(199, 230, 71, 20));
        label_101->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        BTN_SAVE_START = new QPushButton(LIGHTWalkingDialog2);
        BTN_SAVE_START->setObjectName(QStringLiteral("BTN_SAVE_START"));
        BTN_SAVE_START->setGeometry(QRect(185, 304, 91, 31));
        BTN_SAVE_END = new QPushButton(LIGHTWalkingDialog2);
        BTN_SAVE_END->setObjectName(QStringLiteral("BTN_SAVE_END"));
        BTN_SAVE_END->setGeometry(QRect(285, 304, 91, 31));
        CON_SAVE_FILENAME = new QLineEdit(LIGHTWalkingDialog2);
        CON_SAVE_FILENAME->setObjectName(QStringLiteral("CON_SAVE_FILENAME"));
        CON_SAVE_FILENAME->setGeometry(QRect(65, 304, 106, 31));
        QFont font2;
        font2.setPointSize(7);
        CON_SAVE_FILENAME->setFont(font2);
        CON_SAVE_FILENAME->setAlignment(Qt::AlignCenter);
        CON_SAVE_FILENAME->setReadOnly(false);
        label_23 = new QLabel(LIGHTWalkingDialog2);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(30, 314, 31, 16));
        QFont font3;
        font3.setPointSize(9);
        label_23->setFont(font3);
        label_23->setAlignment(Qt::AlignCenter);

        retranslateUi(LIGHTWalkingDialog2);

        QMetaObject::connectSlotsByName(LIGHTWalkingDialog2);
    } // setupUi

    void retranslateUi(QDialog *LIGHTWalkingDialog2)
    {
        LIGHTWalkingDialog2->setWindowTitle(QApplication::translate("LIGHTWalkingDialog2", "Dialog", Q_NULLPTR));
        groupBox->setTitle(QApplication::translate("LIGHTWalkingDialog2", "[ Operation Target ]", Q_NULLPTR));
        RBTN_OPERATIONMODE_ROBOT->setText(QApplication::translate("LIGHTWalkingDialog2", "Robot", Q_NULLPTR));
        RBTN_OPERATIONMODE_CHOREONOID->setText(QApplication::translate("LIGHTWalkingDialog2", "Choreonoid", Q_NULLPTR));
        label_46->setText(QApplication::translate("LIGHTWalkingDialog2", "Current Mode : ", Q_NULLPTR));
        LE_ROBOT_OR_SIM->setText(QString());
        groupBox_4->setTitle(QApplication::translate("LIGHTWalkingDialog2", "[ Robot(LIGHT) Control Mode ]", Q_NULLPTR));
        BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_POS->setText(QApplication::translate("LIGHTWalkingDialog2", "ALL Joint Change to Pos. Ctrl.", Q_NULLPTR));
        CBX_ROBOT_CONTROLMETHOD_RHY->setText(QApplication::translate("LIGHTWalkingDialog2", "RHY", Q_NULLPTR));
        CBX_ROBOT_CONTROLMETHOD_RHR->setText(QApplication::translate("LIGHTWalkingDialog2", "RHR", Q_NULLPTR));
        CBX_ROBOT_CONTROLMETHOD_RHP->setText(QApplication::translate("LIGHTWalkingDialog2", "RHP", Q_NULLPTR));
        CBX_ROBOT_CONTROLMETHOD_RKN->setText(QApplication::translate("LIGHTWalkingDialog2", "RKN", Q_NULLPTR));
        CBX_ROBOT_CONTROLMETHOD_RANK->setText(QApplication::translate("LIGHTWalkingDialog2", "RANK(Both)", Q_NULLPTR));
        CBX_ROBOT_CONTROLMETHOD_LHY->setText(QApplication::translate("LIGHTWalkingDialog2", "LHY", Q_NULLPTR));
        CBX_ROBOT_CONTROLMETHOD_LANK->setText(QApplication::translate("LIGHTWalkingDialog2", "LANK(Both)", Q_NULLPTR));
        CBX_ROBOT_CONTROLMETHOD_LHP->setText(QApplication::translate("LIGHTWalkingDialog2", "LHP", Q_NULLPTR));
        CBX_ROBOT_CONTROLMETHOD_LHR->setText(QApplication::translate("LIGHTWalkingDialog2", "LHR", Q_NULLPTR));
        CBX_ROBOT_CONTROLMETHOD_LKN->setText(QApplication::translate("LIGHTWalkingDialog2", "LKN", Q_NULLPTR));
        BTN_ROBOT_CONTROLMETHOD_CHANGE->setText(QApplication::translate("LIGHTWalkingDialog2", "Mode Change", Q_NULLPTR));
        BTN_ROBOT_CONTROLMETHOD_CHANGE_TO_TOR->setText(QApplication::translate("LIGHTWalkingDialog2", "ALL Joint Change to Tor. Ctrl.", Q_NULLPTR));
        label_42->setText(QApplication::translate("LIGHTWalkingDialog2", "(Checked :Unchecked : Position Control,  Torque Control)", Q_NULLPTR));
        groupBox_3->setTitle(QApplication::translate("LIGHTWalkingDialog2", "[IMU Handling]", Q_NULLPTR));
        BTN_IMU_NULL->setText(QApplication::translate("LIGHTWalkingDialog2", "Nulling", Q_NULLPTR));
        LE_IMU_ROLL->setText(QString());
        label_43->setText(QApplication::translate("LIGHTWalkingDialog2", "R", Q_NULLPTR));
        label_44->setText(QApplication::translate("LIGHTWalkingDialog2", "P", Q_NULLPTR));
        label_45->setText(QApplication::translate("LIGHTWalkingDialog2", "Y", Q_NULLPTR));
        BTN_IMU_RESET->setText(QApplication::translate("LIGHTWalkingDialog2", "Reset", Q_NULLPTR));
        BTN_IMU_ENABLE->setText(QApplication::translate("LIGHTWalkingDialog2", "Enable", Q_NULLPTR));
        BTN_IMU_DISABLE->setText(QApplication::translate("LIGHTWalkingDialog2", "Disable", Q_NULLPTR));
        LE_IMU_PITCH->setText(QString());
        LE_IMU_YAW->setText(QString());
        label->setText(QApplication::translate("LIGHTWalkingDialog2", "LIGHT Walking Dialog Page 2", Q_NULLPTR));
        BTN_COM_SMOOTH_MOTION_GO->setText(QApplication::translate("LIGHTWalkingDialog2", "To Right Foot", Q_NULLPTR));
        label_52->setText(QApplication::translate("LIGHTWalkingDialog2", "<CoM Smooth Motion>", Q_NULLPTR));
        BTN_RFSWINGUP_GO->setText(QApplication::translate("LIGHTWalkingDialog2", "Right Foot\n"
"Swing Up", Q_NULLPTR));
        label_53->setText(QApplication::translate("LIGHTWalkingDialog2", "<Foot Swing Up Motion>", Q_NULLPTR));
        BTN_RFSWINGDOWN_GO->setText(QApplication::translate("LIGHTWalkingDialog2", "Right Foot\n"
"Swing Down", Q_NULLPTR));
        BTN_COM_SMOOTH_MOTION_GO_LDSP->setText(QApplication::translate("LIGHTWalkingDialog2", "To Left Foot", Q_NULLPTR));
        BTN_LFSWINGDOWN_GO->setText(QApplication::translate("LIGHTWalkingDialog2", "Left Foot\n"
"Swing Down", Q_NULLPTR));
        BTN_LFSWINGUP_GO->setText(QApplication::translate("LIGHTWalkingDialog2", "Left Foot\n"
"Swing Up", Q_NULLPTR));
        label_40->setText(QApplication::translate("LIGHTWalkingDialog2", "-->", Q_NULLPTR));
        label_54->setText(QApplication::translate("LIGHTWalkingDialog2", "-->", Q_NULLPTR));
        groupBox_5->setTitle(QString());
        BTN_JOYSTICK_ENABLE->setText(QApplication::translate("LIGHTWalkingDialog2", "JoyStick\n"
"Enable", Q_NULLPTR));
        BTN_JOYSTICK_DISABLE->setText(QApplication::translate("LIGHTWalkingDialog2", "JoyStick\n"
"Disable", Q_NULLPTR));
        LE_JOYSTICK_COMMAND_X->setText(QString());
        LE_JOYSTICK_COMMAND_Y->setText(QString());
        LE_JOYSTICK_COMMAND_YAW->setText(QString());
        label_47->setText(QApplication::translate("LIGHTWalkingDialog2", "Command X", Q_NULLPTR));
        label_48->setText(QApplication::translate("LIGHTWalkingDialog2", "Command Y", Q_NULLPTR));
        label_49->setText(QApplication::translate("LIGHTWalkingDialog2", "Command Yaw", Q_NULLPTR));
        label_58->setText(QApplication::translate("LIGHTWalkingDialog2", "sec", Q_NULLPTR));
        label_64->setText(QApplication::translate("LIGHTWalkingDialog2", "m", Q_NULLPTR));
        label_59->setText(QApplication::translate("LIGHTWalkingDialog2", "Step Number", Q_NULLPTR));
        label_65->setText(QApplication::translate("LIGHTWalkingDialog2", "X-Offset", Q_NULLPTR));
        label_57->setText(QApplication::translate("LIGHTWalkingDialog2", "m", Q_NULLPTR));
        label_66->setText(QApplication::translate("LIGHTWalkingDialog2", "sec", Q_NULLPTR));
        label_67->setText(QApplication::translate("LIGHTWalkingDialog2", "DSP Time", Q_NULLPTR));
        label_60->setText(QApplication::translate("LIGHTWalkingDialog2", "Step Time", Q_NULLPTR));
        label_61->setText(QApplication::translate("LIGHTWalkingDialog2", "steps", Q_NULLPTR));
        label_68->setText(QApplication::translate("LIGHTWalkingDialog2", "m", Q_NULLPTR));
        CON_DYNAMICWALKING_STEP_NUMBER->setText(QApplication::translate("LIGHTWalkingDialog2", "4", Q_NULLPTR));
        label_71->setText(QApplication::translate("LIGHTWalkingDialog2", "deg", Q_NULLPTR));
        CON_DYNAMICWALKING_YAW_ROTATION->setText(QApplication::translate("LIGHTWalkingDialog2", "0.0", Q_NULLPTR));
        label_73->setText(QApplication::translate("LIGHTWalkingDialog2", "Y-dir. Step", Q_NULLPTR));
        CON_DYNAMICWALKING_SWAY_LENGTH->setText(QApplication::translate("LIGHTWalkingDialog2", "0.210", Q_NULLPTR));
        label_55->setText(QApplication::translate("LIGHTWalkingDialog2", "X-dir. Step", Q_NULLPTR));
        label_74->setText(QApplication::translate("LIGHTWalkingDialog2", "Yaw Offset", Q_NULLPTR));
        label_75->setText(QApplication::translate("LIGHTWalkingDialog2", "deg", Q_NULLPTR));
        label_69->setText(QApplication::translate("LIGHTWalkingDialog2", "Y-Offset", Q_NULLPTR));
        label_56->setText(QApplication::translate("LIGHTWalkingDialog2", "<Dynamic Walking Motion>", Q_NULLPTR));
        BTN_DYNAMICWALKING_GO->setText(QApplication::translate("LIGHTWalkingDialog2", "Start Walking\n"
"(GUI Command)", Q_NULLPTR));
        label_70->setText(QApplication::translate("LIGHTWalkingDialog2", "Yaw Rotation", Q_NULLPTR));
        label_63->setText(QApplication::translate("LIGHTWalkingDialog2", "m", Q_NULLPTR));
        BTN_DYNAMICWALKING_JOYSTICK_GO->setText(QApplication::translate("LIGHTWalkingDialog2", "Start Walking\n"
"(JoyStick Command)", Q_NULLPTR));
        CON_DYNAMICWALKING_OFFSET_YAW->setText(QApplication::translate("LIGHTWalkingDialog2", "0.0", Q_NULLPTR));
        CON_DYNAMICWALKING_DSP_TIME->setText(QApplication::translate("LIGHTWalkingDialog2", "0.06", Q_NULLPTR));
        label_72->setText(QApplication::translate("LIGHTWalkingDialog2", "m", Q_NULLPTR));
        CON_DYNAMICWALKING_Y_STEP->setText(QApplication::translate("LIGHTWalkingDialog2", "0.00", Q_NULLPTR));
        label_76->setText(QApplication::translate("LIGHTWalkingDialog2", "X-direction Step : -0.30 ~ 0.30 [m]\n"
"Y-direction Step : -0.10 ~ 0.10 [m]\n"
"Yaw-rotation Step : -15.0 ~ 15.0 [deg]", Q_NULLPTR));
        CON_DYNAMICWALKING_STEP_TIME->setText(QApplication::translate("LIGHTWalkingDialog2", "0.60", Q_NULLPTR));
        CON_DYNAMICWALKING_X_STEP->setText(QApplication::translate("LIGHTWalkingDialog2", "0.00", Q_NULLPTR));
        CON_DYNAMICWALKING_OFFSET_X->setText(QApplication::translate("LIGHTWalkingDialog2", "0.00", Q_NULLPTR));
        CON_DYNAMICWALKING_OFFSET_Y->setText(QApplication::translate("LIGHTWalkingDialog2", "0.01", Q_NULLPTR));
        label_62->setText(QApplication::translate("LIGHTWalkingDialog2", "Sway Length", Q_NULLPTR));
        label_100->setText(QApplication::translate("LIGHTWalkingDialog2", "m", Q_NULLPTR));
        CON_DYNAMICWALKING_STANCE_OFFSET->setText(QApplication::translate("LIGHTWalkingDialog2", "0.025", Q_NULLPTR));
        label_101->setText(QApplication::translate("LIGHTWalkingDialog2", "Stance Off.", Q_NULLPTR));
        BTN_SAVE_START->setText(QApplication::translate("LIGHTWalkingDialog2", "Save Start", Q_NULLPTR));
        BTN_SAVE_END->setText(QApplication::translate("LIGHTWalkingDialog2", "Save End", Q_NULLPTR));
        CON_SAVE_FILENAME->setText(QString());
        label_23->setText(QApplication::translate("LIGHTWalkingDialog2", "Title", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class LIGHTWalkingDialog2: public Ui_LIGHTWalkingDialog2 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_LIGHTWALKINGDIALOG2_H
