
#ifndef SOLVER_PUMPPRESSURECONTROL_CASADI_H
#define SOLVER_PUMPPRESSURECONTROL_CASADI_H

/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

int Solver_PumpPressureControl_objective0rd_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void Solver_PumpPressureControl_objective0rd_1_incref(void);

const casadi_int* Solver_PumpPressureControl_objective0rd_1_sparsity_out(casadi_int i);

int Solver_PumpPressureControl_objective1rd_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void Solver_PumpPressureControl_objective1rd_1_incref(void);

const casadi_int* Solver_PumpPressureControl_objective1rd_1_sparsity_out(casadi_int i);

int Solver_PumpPressureControl_dynamics_0rd_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void Solver_PumpPressureControl_dynamics_0rd_0_incref(void);

const casadi_int* Solver_PumpPressureControl_dynamics_0rd_0_sparsity_out(casadi_int i);

int Solver_PumpPressureControl_dynamics_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void Solver_PumpPressureControl_dynamics_0_incref(void);

const casadi_int* Solver_PumpPressureControl_dynamics_0_sparsity_out(casadi_int i);

int Solver_PumpPressureControl_objective0rd_16(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void Solver_PumpPressureControl_objective0rd_16_incref(void);

const casadi_int* Solver_PumpPressureControl_objective0rd_16_sparsity_out(casadi_int i);

int Solver_PumpPressureControl_objective1rd_16(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void Solver_PumpPressureControl_objective1rd_16_incref(void);

const casadi_int* Solver_PumpPressureControl_objective1rd_16_sparsity_out(casadi_int i);

#ifdef __cplusplus
} /* extern "C" */
#endif
#endif
