/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Solver_PumpPressureControl_casadi_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)

/* Symbol visibility in DLLs */
#if 0
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s4[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s5[6] = {1, 2, 0, 0, 1, 0};
static const casadi_int casadi_s6[7] = {2, 2, 0, 2, 2, 0, 1};

/* Solver_PumpPressureControl_objective0rd_1:(i0[3],i1,i2[],i3[])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
    a0=5.0000000000000000e-001;
    a1=3.1622776601683793e+001;
    a2=arg[0]? arg[0][1] : 0;
    a3=arg[1]? arg[1][0] : 0;
    a4=5.;
    a5=(a3+a4);
    a5=(a2-a5);
    a5=(a1*a5);
    a3=(a3+a4);
    a2=(a2-a3);
    a1=(a1*a2);
    a5=(a5*a1);
    a0=(a0*a5);
    if (res[0]!=0) res[0][0]=a0;
    return 0;
}

int Solver_PumpPressureControl_objective0rd_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f0(arg, res, iw, w, mem);
}

const casadi_int* Solver_PumpPressureControl_objective0rd_1_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s1;
        default: return 0;
    }
}

/* Solver_PumpPressureControl_objective1rd_1:(i0[3],i1,i2[],i3[])->(o0[1x3,1nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
    a0=5.0000000000000000e-001;
    a1=3.1622776601683793e+001;
    a2=arg[0]? arg[0][1] : 0;
    a3=arg[1]? arg[1][0] : 0;
    a4=5.;
    a5=(a3+a4);
    a5=(a2-a5);
    a5=(a1*a5);
    a5=(a1*a5);
    a3=(a3+a4);
    a2=(a2-a3);
    a2=(a1*a2);
    a1=(a1*a2);
    a5=(a5+a1);
    a0=(a0*a5);
    if (res[0]!=0) res[0][0]=a0;
    return 0;
}

int Solver_PumpPressureControl_objective1rd_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f1(arg, res, iw, w, mem);
}

const casadi_int* Solver_PumpPressureControl_objective1rd_1_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s3;
        default: return 0;
    }
}

/* Solver_PumpPressureControl_dynamics_0rd_0:(i0[2],i1,i2)->(o0[2]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
    a0=2.7999999999999998e+000;
    a1=arg[0]? arg[0][0] : 0;
    a2=60.;
    a3=(a1/a2);
    a4=7.1428571428571430e-001;
    a3=pow(a3,a4);
    a0=(a0*a3);
    a0=(a0*a1);
    a3=4.9815497187763241e-004;
    a4=arg[0]? arg[0][1] : 0;
    a3=(a3*a4);
    a3=(a2*a3);
    a4=1.7142857142857144e-002;
    a4=(a4*a1);
    a3=(a3-a4);
    a0=(a0*a3);
    a0=(a0/a2);
    if (res[0]!=0) res[0][0]=a0;
    a0=arg[1]? arg[1][0] : 0;
    if (res[0]!=0) res[0][1]=a0;
    return 0;
}

int Solver_PumpPressureControl_dynamics_0rd_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f2(arg, res, iw, w, mem);
}

const casadi_int* Solver_PumpPressureControl_dynamics_0rd_0_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s4;
        default: return 0;
    }
}

/* Solver_PumpPressureControl_dynamics_0:(i0[2],i1,i2)->(o0[2],o1[1x2,1nz],o2[2x2,2nz]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8;
    a0=2.7999999999999998e+000;
    a1=arg[0]? arg[0][0] : 0;
    a2=60.;
    a3=(a1/a2);
    a4=7.1428571428571430e-001;
    a5=pow(a3,a4);
    a5=(a0*a5);
    a6=(a5*a1);
    a7=4.9815497187763241e-004;
    a8=arg[0]? arg[0][1] : 0;
    a7=(a7*a8);
    a7=(a2*a7);
    a8=1.7142857142857144e-002;
    a8=(a8*a1);
    a7=(a7-a8);
    a8=(a6*a7);
    a8=(a8/a2);
    if (res[0]!=0) res[0][0]=a8;
    a8=arg[1]? arg[1][0] : 0;
    if (res[0]!=0) res[0][1]=a8;
    a8=1.;
    if (res[1]!=0) res[1][0]=a8;
    a8=1.6666666666666666e-002;
    a2=-2.8571428571428570e-001;
    a3=pow(a3,a2);
    a4=(a4*a3);
    a4=(a8*a4);
    a0=(a0*a4);
    a1=(a1*a0);
    a1=(a1+a5);
    a7=(a7*a1);
    a1=-1.7142857142857144e-002;
    a1=(a1*a6);
    a7=(a7+a1);
    a7=(a8*a7);
    if (res[2]!=0) res[2][0]=a7;
    a7=2.9889298312657943e-002;
    a7=(a7*a6);
    a8=(a8*a7);
    if (res[2]!=0) res[2][1]=a8;
    return 0;
}

int Solver_PumpPressureControl_dynamics_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f3(arg, res, iw, w, mem);
}

const casadi_int* Solver_PumpPressureControl_dynamics_0_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s4;
        case 1: return casadi_s5;
        case 2: return casadi_s6;
        default: return 0;
    }
}

/* Solver_PumpPressureControl_objective0rd_16:(i0[3],i1,i2[],i3[])->(o0) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
    a0=5.0000000000000000e-001;
    a1=3.1622776601683793e+001;
    a2=arg[0]? arg[0][1] : 0;
    a3=arg[1]? arg[1][0] : 0;
    a4=5.;
    a5=(a3+a4);
    a5=(a2-a5);
    a5=(a1*a5);
    a3=(a3+a4);
    a2=(a2-a3);
    a1=(a1*a2);
    a5=(a5*a1);
    a0=(a0*a5);
    if (res[0]!=0) res[0][0]=a0;
    return 0;
}

int Solver_PumpPressureControl_objective0rd_16(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f4(arg, res, iw, w, mem);
}

const casadi_int* Solver_PumpPressureControl_objective0rd_16_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s1;
        default: return 0;
    }
}

/* Solver_PumpPressureControl_objective1rd_16:(i0[3],i1,i2[],i3[])->(o0[1x3,1nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
    a0=5.0000000000000000e-001;
    a1=3.1622776601683793e+001;
    a2=arg[0]? arg[0][1] : 0;
    a3=arg[1]? arg[1][0] : 0;
    a4=5.;
    a5=(a3+a4);
    a5=(a2-a5);
    a5=(a1*a5);
    a5=(a1*a5);
    a3=(a3+a4);
    a2=(a2-a3);
    a2=(a1*a2);
    a1=(a1*a2);
    a5=(a5+a1);
    a0=(a0*a5);
    if (res[0]!=0) res[0][0]=a0;
    return 0;
}

int Solver_PumpPressureControl_objective1rd_16(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f5(arg, res, iw, w, mem);
}

const casadi_int* Solver_PumpPressureControl_objective1rd_16_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s3;
        default: return 0;
    }
}

#ifdef __cplusplus
} /* extern "C" */
#endif
